/* Account-bound call controller. Incoming signalling never opens microphone automatically. */
(function(root){'use strict';
 const UUID=/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i;
 let pending=null;
 try{const u=new URL(root.location.href);if(u.searchParams.has('call')){const id=u.searchParams.get('call'),recipient=u.searchParams.get('recipient');if(UUID.test(id||'')&&UUID.test(recipient||'')&&u.searchParams.getAll('call').length===1&&u.searchParams.getAll('recipient').length===1)pending={id,recipient};u.searchParams.delete('call');u.searchParams.delete('recipient');root.history.replaceState(root.history.state,'',u.pathname+u.search+u.hash);}}catch{}
 function create({client,getUser,onChange=()=>{},onLocalStream=()=>{},onRemoteStream=()=>{}}={}){
  let owner=null,sessionKey=null,epoch=0,operation=0,device=root.crypto.randomUUID(),call=null,media=null,available=false,reason='disabled',provider=null,phase='idle',cursor=0,signalGeneration=1,poll=null,deadline=null,channel=null,reconciling=null,outbound=Promise.resolve(),muted=false,video=true,lastHeartbeat=0,restartBusy=false,iceExpiry=0,failureSince=0;
  const account=()=>getUser?.()?.id||null,valid=(g,u)=>g===epoch&&u===owner&&u===account();
  const snapshot=()=>({call:call?{...call}:null,available,reason,phase,muted,video,owner});
  function paint(){onChange(snapshot());}
  function stopMedia(){const m=media;media=null;m?.hangup();onLocalStream(null);onRemoteStream(null);clearTimeout(deadline);deadline=null;}
  function localEnd(message='ended'){failureSince=0;muted=false;video=true;operation++;stopMedia();call=null;cursor=0;phase=message;paint();}
  async function rpc(action,input={},g=epoch,u=owner){if(!valid(g,u))throw Error('session_changed');let timer;const request=client.rpc('pablicus_calls',{p_action:action,p_input:input});try{const r=await Promise.race([request,new Promise((_,reject)=>{timer=root.setTimeout(()=>reject(Error('timeout')),10000);})]);if(!valid(g,u))throw Error('session_changed');if(r?.error)throw Error('network');if(!r?.data?.ok)throw Error(r?.data?.error||'unavailable');return r.data;}finally{root.clearTimeout(timer);}}
  function arm(ms){clearTimeout(deadline);const g=epoch,id=call?.id;deadline=root.setTimeout(()=>{if(g===epoch&&call?.id===id)void end('timeout');},ms);}
  function send(signal){const g=epoch,u=owner,id=call?.id,gen=signalGeneration;const input={call_id:id,device_id:device,client_id:root.crypto.randomUUID(),generation:gen,kind:signal.type==='candidate'?'ice':signal.description.type,payload:signal.type==='candidate'?signal.candidate:signal.description};const p=outbound.then(()=>{if(!valid(g,u)||call?.id!==id)throw Error('cancelled');return rpc('signal',input,g,u);});outbound=p.catch(()=>{});return p;}
  async function recovery(){if(restartBusy||!call||call.caller_id!==owner||!media)return;restartBusy=true;const g=epoch,id=call.id;try{if(iceExpiry<Date.now()+60000){const config=await iceConfig();if(call?.id!==id)return;media.configure(config.iceServers);}const r=await rpc('restart',{call_id:id,device_id:device});if(!valid(g,owner)||call?.id!==id)return;signalGeneration=r.call?.generation||r.generation;if(!Number.isInteger(signalGeneration))throw Error('generation');await media.restart();}catch{if(g===epoch&&call?.id===id)void end('connection-failed');}finally{restartBusy=false;}}
  function connection(state){if(!call||!media)return;if(state==='connected'){phase='connected';failureSince=0;clearTimeout(deadline);deadline=null;void heartbeat(true);}else if(state==='disconnected'||state==='failed'){phase='reconnecting';if(!failureSince){failureSince=Date.now();arm(20000);}void recovery();}else if(state==='signalling-failed'){void end('connection-failed');}else if(state==='connecting'){phase='connecting';}paint();}
  async function iceConfig(g=epoch,u=owner){let config;if(provider==='cloudflare'){let timer;let result;try{result=await Promise.race([client.functions.invoke('pablicus-calls-ice',{body:{call_id:call.id,device_id:device}}),new Promise((_,reject)=>{timer=root.setTimeout(()=>reject(Error('timeout')),10000);})]);}finally{root.clearTimeout(timer);}if(!valid(g,u)||result.error||!result.data?.ok)throw Error('turn_unavailable');config={...result.data,iceServers:result.data.ice_servers,iceTransportPolicy:'relay'};}else config=await rpc('ice',{call_id:call.id,device_id:device},g,u);iceExpiry=Date.parse(config.expires_at);if(!Number.isFinite(iceExpiry)||iceExpiry<=Date.now()+30000)throw Error('turn_expired');return config;}
  async function prepare(g,u,op){const config=await iceConfig(g,u);if(op!==operation||!call)return false;if(config.iceTransportPolicy!=='relay'||!Array.isArray(config.iceServers)||!config.iceServers.some(s=>(Array.isArray(s.urls)?s.urls:[s.urls]).some(v=>/^turns?:/.test(v))&&s.username&&s.credential))throw Error('turn_unconfigured');media=root.PablicusCalls.create({iceServers:config.iceServers,iceTransportPolicy:'relay',onSignal:send,onState:connection,onLocalStream,onRemoteStream});return true;}
  async function start(conversationId,kind='audio'){if(call||phase==='checking'||!owner||!UUID.test(conversationId||'')||!['audio','video'].includes(kind))return false;const g=epoch,u=owner,op=++operation;muted=false;video=kind==='video';phase='checking';paint();try{const state=await rpc('state',{},g,u);if(op!==operation)return false;available=state.available===true;reason=state.reason;provider=state.ice_provider||'coturn';if(!available){phase='unavailable';paint();return false;}const r=await rpc('create',{conversation_id:conversationId,client_id:root.crypto.randomUUID(),device_id:device,media:kind},g,u);if(op!==operation){if(r.call?.id)void rpc('cancel',{call_id:r.call.id,device_id:device},g,u).catch(()=>{});return false;}call=r.call;signalGeneration=call.generation;cursor=0;phase='ringing';paint();arm(45000);if(!await prepare(g,u,op))return false;await media.start({video:kind==='video'});if(!valid(g,u)||op!==operation)return false;void reconcile();return true;}catch(e){if(valid(g,u)&&op===operation){if(call)void end('failed');else{phase=e.message==='timeout'?'timeout':'unavailable';paint();}}return false;}}
  async function accept(){if(!call||call.status!=='ringing'||call.callee_id!==owner||phase==='accepting')return false;const g=epoch,u=owner,id=call.id,op=++operation;muted=false;video=call.media==='video';phase='accepting';paint();try{const r=await rpc('accept',{call_id:id,device_id:device},g,u);if(op!==operation){void rpc('end',{call_id:id,device_id:device},g,u).catch(()=>{});return false;}call=r.call;signalGeneration=call.generation;phase='connecting';paint();arm(45000);if(!await prepare(g,u,op))return false;await reconcile();return true;}catch{if(valid(g,u)&&op===operation)void end('unavailable');return false;}}
  async function end(why='ended'){const old=call,g=epoch,u=owner;localEnd(why);if(!old||!valid(g,u))return;const action=old.status==='ringing'?(old.caller_id===u?'cancel':'reject'):'end';try{await rpc(action,{call_id:old.id,device_id:device},g,u);}catch{if(action==='cancel'&&valid(g,u))try{await rpc('end',{call_id:old.id,device_id:device},g,u);}catch{}/* Server lease expires; never resurrect local media. */}}
  async function heartbeat(connected=phase==='connected'){if(!call||!media||Date.now()-lastHeartbeat<10000)return;lastHeartbeat=Date.now();try{if(iceExpiry<Date.now()+60000){const id=call.id,config=await iceConfig();if(call?.id!==id||!media)return;media.configure(config.iceServers);}const d=await rpc('heartbeat',{call_id:call.id,device_id:device,connected});if(d.call?.status==='ended')localEnd('ended');}catch{void end('connection-failed');}}
  async function reconcile(){if(!owner||account()!==owner)return;if(reconciling)return reconciling;const g=epoch,u=owner;reconciling=(async()=>{try{const expectedOperation=operation;const state=await rpc('state',{},g,u);if(expectedOperation!==operation)return;available=state.available===true;reason=state.reason;provider=state.ice_provider||'coturn';if(!available){if(call)localEnd('unavailable');paint();return;}if(!call){const incoming=(state.calls||[]).find(c=>c.status==='ringing'&&c.callee_id===u&&(!pending||pending.recipient!==u||pending.id===c.id));if(incoming){call=incoming;phase='incoming';arm(Math.min(45000,Math.max(1,Date.parse(call.expires_at)-Date.now())));paint();}pending=null;paint();return;}const id=call.id,active=(state.calls||[]).find(c=>c.id===id);if(!active||active.status==='ended'){localEnd('ended');return;}if((active.caller_id===u&&active.caller_device!==device)||(active.callee_id===u&&active.callee_device&&active.callee_device!==device)){localEnd('other-device');return;}call=active;if(!media){paint();return;}const data=await rpc('sync',{call_id:id,device_id:device,after:cursor},g,u);if(call?.id!==id)return;if(data.call?.status==='ended'){localEnd('ended');return;}for(const s of data.signals||[]){if(!media||call?.id!==id)return;if(s.generation<signalGeneration){cursor=Math.max(cursor,s.seq);continue;}signalGeneration=s.generation;await media.accept(s.kind==='ice'?{type:'candidate',candidate:s.payload,generation:s.generation}:{type:'description',description:s.payload,generation:s.generation},{video:call.media==='video'});cursor=Math.max(cursor,s.seq);}cursor=Math.max(cursor,data.cursor||0);if(call&&media)await heartbeat();paint();}catch(e){if(valid(g,u)&&call){if(['not_allowed','session_changed','other_device','unavailable','revoked'].includes(e.message)){localEnd('unavailable');return;}phase='reconnecting';paint();if(!failureSince){failureSince=Date.now();arm(20000);}}}})().finally(()=>{if(g===epoch)reconciling=null;});return reconciling;}
  function clear(){epoch++;operation++;owner=null;sessionKey=null;muted=false;video=true;available=false;reason='disabled';stopMedia();call=null;phase='idle';cursor=0;outbound=Promise.resolve();reconciling=null;clearTimeout(poll);poll=null;if(channel){void client.removeChannel?.(channel);channel=null;}paint();}
  function ready(session){const u=account();let key=u;try{key=JSON.parse(root.atob(session.access_token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/'))).session_id||u;}catch{}if(u===owner&&key===sessionKey){void reconcile();return;}clear();if(!u)return;owner=u;sessionKey=key;device=root.crypto.randomUUID();const g=epoch;const tick=async()=>{if(g!==epoch)return;await reconcile();if(g===epoch)poll=root.setTimeout(tick,call?1500:15000);};if(client.channel){channel=client.channel('pablicus-calls-'+device).on('postgres_changes',{event:'*',schema:'public',table:'pablicus_call_wakeups',filter:'user_id=eq.'+u},()=>void reconcile()).subscribe();}void tick();}
  root.addEventListener?.('online',()=>void reconcile());root.addEventListener?.('pageshow',()=>void reconcile());root.document?.addEventListener('visibilitychange',()=>{if(root.document.visibilityState==='visible')void reconcile();});root.navigator?.serviceWorker?.addEventListener('message',e=>{const d=e.data;if(d?.type==='PABLICUS_CALL_OPEN'&&UUID.test(d.callId||'')&&d.recipientId===owner){pending={id:d.callId,recipient:owner};void reconcile();}});
  return{ready,clear,start,accept,end,reconcile,snapshot,setMuted(v){muted=!!v;media?.setMuted(muted);paint();},setVideo(v){video=!!v;media?.setVideo(video);paint();}};
 }
 root.PablicusCallClient=Object.freeze({create});
})(typeof window!=='undefined'?window:globalThis);
