/* Public profile plus viewer-private nickname/note. Never writes another profile. */
(function(scope){'use strict';
 const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n};
 const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
 const personalName=p=>[p?.first_name,p?.last_name].map(v=>typeof v==='string'?v.trim():'').filter(Boolean).join(' ');
 const profileName=p=>p?.display_name?.trim()||(p?.username?'@'+p.username:'Контакт');
 const nameOf=data=>personalName(data?.personal)||profileName(data?.profile);
 const initial=name=>Array.from(String(name||'?').replace(/^@/,''))[0]?.toUpperCase()||'?';
 function create(o){
  const client=o.client,controller=o.controller;
  let state=null,dirty=false,busy=false,returnFocus=null,headBusy=false,lastRoute=null;
  const lifetime=new AbortController(),urlCache=new Map();
  const page=el('dialog','contactPage');page.id='pablicusContactCard';page.setAttribute('aria-label','Карточка контакта');page.tabIndex=-1;document.body.append(page);
  const identity=()=>controller.state();
  const session=s=>!!s&&identity().sessionUserId===s.owner&&identity().sessionGeneration===s.generation;
  const live=s=>state===s&&session(s)&&page.open&&!s.abort.signal.aborted;
  async function read(request,s){const r=await(request.abortSignal?request.abortSignal(s.abort.signal):request);if(!live(s))throw new DOMException('Карточка закрыта','AbortError');if(r.error)throw r.error;return r.data;}
  const errorText=e=>e?.code==='40001'?'Контакт изменён на другом устройстве. Закройте редактирование и откройте его заново.':e?.code==='42501'?'Этот профиль недоступен вашему аккаунту.':e?.code==='22023'?'Проверьте имя и длину заметки.':'Не удалось загрузить или сохранить данные. Проверьте интернет и повторите.';
  function report(e,s=state){if(live(s)){const box=page.querySelector('.contactStatus');if(box){box.textContent=errorText(e);box.setAttribute('role','alert');}else o.notify?.(errorText(e));}}
  function btn(label,run,icon,cls=''){const b=el('button','contactButton '+cls);b.type='button';b.setAttribute('aria-label',label);if(icon&&scope.PablicusMessageMenu?.icon)b.append(scope.PablicusMessageMenu.icon(icon));b.append(el('span','',label));b.onclick=()=>Promise.resolve().then(run).catch(e=>report(e));return b;}
  function disposeMedia(){page.querySelectorAll('video').forEach(v=>{v.pause();v.removeAttribute('src');v.load();});}
  function clearPage(){disposeMedia();page.replaceChildren();page.scrollTop=0;}
  function close(force=false){if(!force&&busy)return false;if(!force&&dirty&&!scope.confirm('Не сохранять изменения контакта?'))return false;if(state)state.abort.abort();state=null;dirty=busy=false;disposeMedia();if(page.open)page.close();page.replaceChildren();if(returnFocus?.isConnected)returnFocus.focus({preventScroll:true});returnFocus=null;return true;}
  function top(editMode=false){const bar=el('header','contactTop');bar.append(btn(editMode?'Отмена':'Назад',()=>{if(editMode){if(busy)return;if(!dirty||scope.confirm('Не сохранять изменения контакта?')){dirty=false;render();}}else close();},editMode?null:'back','contactBack'));if(!editMode&&state?.data?.kind==='contact')bar.append(btn('Изм.',edit,null,'contactEdit'));page.append(bar);return bar;}
  async function imageUrl(path,person,s){
   if(typeof path!=='string'||!path)return '';
   if(/^https:\/\//i.test(path)){const u=new URL(path);if(u.username||u.password)throw Error('Invalid avatar');return u.href;}
   if(!UUID.test(person||'')||!path.startsWith(person+'/')||path.includes('..')||!/^[a-z0-9_/-]+\.(jpe?g|png|webp|gif|mp4|mov|webm)$/i.test(path))throw Error('Invalid media');
   const cached=urlCache.get(path);if(cached?.until>Date.now())return cached.url;
   const r=await client.storage.from('profile-media').createSignedUrl(path,300);if(!session(s))throw Error('Account changed');if(r.error)throw r.error;
   const u=new URL(r.data?.signedUrl);if(u.protocol!=='https:'||u.username||u.password)throw Error('Invalid media URL');urlCache.set(path,{url:u.href,until:Date.now()+240000});return u.href;
  }
  function face(p,s,cls='contactFace'){const n=el('div',cls,initial(nameOf(s.data)));if(p.avatar_url)imageUrl(p.avatar_url,p.id,s).then(url=>{if(!live(s)||!n.isConnected)return;const img=el('img');img.alt='Фотография профиля';img.referrerPolicy='no-referrer';img.draggable=false;img.onload=()=>{if(live(s)&&n.isConnected)n.replaceChildren(img)};img.onerror=()=>{};img.src=url;}).catch(()=>{});return n;}
  function row(label,value,action){const n=el('div','contactInfoRow');n.append(el('span','contactLabel',label));n.append(action?btn(value,action,null,'contactTextButton'):el('div','contactValue',value));return n;}
  async function share(){const s=state;if(!live(s))return;const p=s.data.profile,url=scope.PablicusPeople.profileLink(p.username);if(navigator.share){try{await navigator.share({title:profileName(p),url});return}catch(e){if(e.name==='AbortError')return;}}if(!live(s))return;try{await navigator.clipboard.writeText(url);if(live(s))o.notify?.('Ссылка на профиль скопирована');}catch{const holder=page.querySelector('.contactStatus');holder.replaceChildren(el('span','','Скопируйте ссылку: '));const input=el('input');input.readOnly=true;input.value=url;input.setAttribute('aria-label','Ссылка на профиль');holder.append(input);input.focus();input.select();}}
  function qr(){const s=state;if(!live(s)||!scope.qrcodegen)return;clearPage();const bar=top();bar.querySelector('.contactBack').onclick=render;bar.querySelector('.contactEdit')?.remove();const box=el('section','contactQr');box.append(face(s.data.profile,s),el('h1','',nameOf(s.data)));const link=scope.PablicusPeople.profileLink(s.data.profile.username),code=scope.qrcodegen.QrCode.encodeText(link,scope.qrcodegen.QrCode.Ecc.MEDIUM),svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox',`-4 -4 ${code.size+8} ${code.size+8}`);svg.setAttribute('role','img');svg.setAttribute('aria-label','QR-код профиля');const path=document.createElementNS(svg.namespaceURI,'path');let d='';for(let y=0;y<code.size;y++)for(let x=0;x<code.size;x++)if(code.getModule(x,y))d+=`M${x},${y}h1v1h-1z `;path.setAttribute('d',d);svg.append(path);box.append(svg,el('p','','@'+s.data.profile.username),btn('Поделиться',share,'share'),el('p','contactStatus',''));page.append(box);}
  async function openChat(tab){const s=state;if(!live(s)||busy)return;const id=s.id,target=(o.getDialogs()||[]).find(d=>d.id===id)||{id,title:nameOf(s.data)};if(dirty&&!scope.confirm('Не сохранять изменения контакта?'))return;close(true);const r=controller.state();if(!['conversation','canvas'].includes(r.screen)||r.conversationId!==id)await o.openConversation(target);if(!session(s)||controller.state().conversationId!==id)return;if(tab)o.openLibrary(tab);}
  async function mute(){const s=state;if(!live(s)||busy)return;busy=true;const node=page.querySelector('[data-contact-action="mute"]');if(node)node.disabled=true;try{const r=await read(client.rpc('pablicus_chat_preferences',{p_action:'mute',p_conversation_id:s.id,p_value:!s.muted}),s);s.muted=!!r.muted;const d=(o.getDialogs()||[]).find(d=>d.id===s.id);if(d)d.muted=s.muted;if(live(s))render();}catch(e){report(e,s)}finally{if(live(s))busy=false;if(node?.isConnected)node.disabled=false;}}
  function render(){const s=state;if(!live(s))return;clearPage();top();const p=s.data.profile,hero=el('section','contactHero'),photo=btn('Открыть фотографию',()=>p.avatar_url?showPhoto():undefined,null,'contactPhotoButton');photo.replaceChildren(face(p,s));hero.append(photo,el('h1','contactName',nameOf(s.data)),el('p','contactHandle contactActivity','Статус активности недоступен'));const actions=el('nav','contactActions');actions.setAttribute('aria-label','Действия контакта');actions.append(btn('Написать',()=>openChat(),'chats'),btn('Поиск',()=>openChat('search'),'search'));const sound=btn(s.muted?'Вкл. звук':'Без звука',mute,s.muted?'notifications':'volumeOff');sound.dataset.contactAction='mute';actions.append(sound,btn('Поделиться',share,'share'));hero.append(actions);page.append(hero);scope.PablicusActivityService?.bind(hero.querySelector('.contactActivity'),s.id);
   const body=el('main','contactBody'),info=el('section','contactInfo');info.append(row('Имя пользователя','@'+p.username,qr),row('Имя в аккаунте',profileName(p)));body.append(info);const own=el('section','contactInfo');own.append(row('Моя заметка',s.data.personal.note||'Добавить заметку',edit));own.append(el('p','contactHint','Имя контакта и заметка видны только вам. Имя и фотография в чужом аккаунте не изменяются.'));body.append(own);body.append(el('p','contactHint','Телефон, день рождения и личные сведения показываются только с разрешения их владельца.'));const tabs=el('nav','contactTabs');tabs.setAttribute('aria-label','Публикации и материалы');tabs.append(btn('Публикации',()=>{page.querySelector('.contactPosts')?.scrollIntoView({block:'start',behavior:'smooth'});}),btn('Медиа',()=>openChat('media')),btn('Файлы',()=>openChat('documents')));body.append(tabs,el('p','contactStatus',''));const posts=el('section','contactPosts');posts.setAttribute('aria-label','Публикации контакта');body.append(posts);page.append(body);if(s.posts)paintPosts(s,posts);else void loadPosts(s,posts);
  }
  async function showPhoto(){const s=state;if(!live(s))return;const p=s.data.profile;if(!p.avatar_url)return;const url=await imageUrl(p.avatar_url,p.id,s);if(!live(s))return;clearPage();const bar=top();bar.querySelector('.contactBack').onclick=render;bar.querySelector('.contactEdit')?.remove();const img=el('img','contactLargePhoto');img.alt='Фотография профиля';img.referrerPolicy='no-referrer';img.src=url;page.append(img);}
  async function loadPosts(s,host,more=false){if(!live(s))return;host.setAttribute('aria-busy','true');try{const offset=more?s.posts.length:0,rows=await read(client.from('pablicus_profile_posts').select('id,body,media,created_at').eq('owner_id',s.data.profile.id).eq('archived',false).order('created_at',{ascending:false}).order('id',{ascending:false}).range(offset,offset+19),s);s.posts=more?[...s.posts,...rows.filter(p=>!s.posts.some(q=>q.id===p.id))]:rows;s.morePosts=rows.length===20;if(live(s)&&host.isConnected)paintPosts(s,host);}catch(e){if(live(s)&&host.isConnected)host.replaceChildren(el('p','contactHint','Публикации не загрузились.'),btn('Повторить',()=>loadPosts(s,host,more)));}finally{host.removeAttribute('aria-busy');}}
  function paintPosts(s,host){host.replaceChildren();if(!s.posts.length){host.append(el('p','contactHint','Открытых публикаций пока нет.'));return;}for(const post of s.posts){const item=el('article','contactPost');if(post.body)item.append(el('p','',post.body));const media=Array.isArray(post.media)?post.media:[];for(const m of media.slice(0,10)){if(!['image','video'].includes(m.type))continue;const n=el(m.type==='video'?'video':'img');if(m.type==='video'){n.controls=true;n.playsInline=true;n.preload='none';}else{n.alt='Фотография публикации';n.loading='lazy';}item.append(n);imageUrl(m.path,s.data.profile.id,s).then(url=>{if(live(s)&&n.isConnected)n.src=url;}).catch(()=>{if(n.isConnected)n.replaceWith(el('p','contactHint','Медиа недоступно'));});}host.append(item);}if(s.morePosts){const more=btn('Ещё публикации',async()=>{more.disabled=true;await loadPosts(s,host,true);});host.append(more);}}
  function edit(){const s=state;if(!live(s)||busy)return;clearPage();const bar=top(true),form=el('form','contactEditForm');form.append(face(s.data.profile,s));const fields=el('section','contactInfo'),pref=s.data.personal;
   function field(label,name,value,max,textarea=false){const wrap=el('label','contactField',label),input=el(textarea?'textarea':'input');input.name=name;input.value=value||'';input.maxLength=max;if(!textarea)input.type='text';input.autocomplete='off';input.oninput=()=>dirty=true;wrap.append(input);fields.append(wrap);return input;}
   const first=field('Имя у меня','first',pref.first_name,80),last=field('Фамилия у меня','last',pref.last_name,80),note=field('Личная заметка','note',pref.note,2000,true);first.placeholder=profileName(s.data.profile);last.placeholder='Необязательно';note.placeholder='Заметку видите только вы';form.append(fields,el('p','contactHint','Можно использовать любое своё имя, в том числе с эмодзи. Это не изменит имя пользователя и его профиль. Пустые поля имени возвращают имя из аккаунта.'));form.append(btn('Вернуть имя из аккаунта',()=>{first.value='';last.value='';dirty=true;},null,'contactReset'));const status=el('p','contactStatus');status.setAttribute('role','alert');form.append(status);const save=btn('Готово',()=>form.requestSubmit(),null,'contactSave');bar.append(save);page.append(form);
   form.onsubmit=async event=>{event.preventDefault();if(busy||!live(s))return;busy=true;save.disabled=true;status.textContent='';try{const personal=await read(client.rpc('pablicus_save_contact',{p_contact_id:s.data.profile.id,p_first_name:first.value.trim(),p_last_name:last.value.trim(),p_note:note.value.trim(),p_expected_revision:s.data.personal.revision}),s);if(!personal||personal.contact_id!==s.data.profile.id)throw Error('Invalid contact response');s.data.personal=personal;dirty=false;applyName(s.data);render();o.notify?.('Контакт сохранён только для вас');}catch(e){if(live(s)){status.textContent=errorText(e);if(e?.code==='40001')status.append(btn('Загрузить сохранённую версию',async()=>{if(!scope.confirm('Загрузить данные с сервера вместо введённых изменений?'))return;dirty=false;busy=false;await open(s.id);}));}}finally{if(live(s))busy=false;save.disabled=false;}};first.focus({preventScroll:true});
  }
  function applyName(data){const ids=new Set(data.conversation_ids||[data.conversation_id]),name=nameOf(data);for(const d of o.getDialogs()||[])if(ids.has(d.id))d.title=name;document.querySelectorAll('.chatCard[data-conversation-id]').forEach(row=>{if(!ids.has(row.dataset.conversationId))return;const n=row.querySelector('.chatText strong');if(n)n.textContent=name;row.querySelector('.contactAvatarTrigger')?.setAttribute('aria-label','Карточка контакта: '+name);});if(ids.has(identity().conversationId))scope.PablicusShell?.conversationTitle(name);}
  async function open(id){if(!UUID.test(id||'')||!identity().sessionUserId)return false;if(page.open&&!close())return false;const i=identity();returnFocus=document.activeElement;const s={owner:i.sessionUserId,generation:i.sessionGeneration,id,abort:new AbortController(),data:null,posts:null,muted:false};state=s;dirty=busy=false;clearPage();top();const content=el('div','contactLoading');content.append(el('p','contactStatus','Загружаем контакт…'));page.append(content);page.showModal();page.focus({preventScroll:true});try{const data=await read(client.rpc('pablicus_contact_card',{p_conversation_id:id}),s);if(!live(s))return false;if(data?.kind==='self'){close(true);await controller.navigate({section:'profile',screen:'home',conversationId:null,resourceId:null});return true;}if(data?.kind==='group'){close(true);const d=(o.getDialogs()||[]).find(d=>d.id===id);if(d)await o.openConversation(d);if(session(s))o.openLibrary('media');return true;}if(data?.kind!=='contact'||!UUID.test(data.profile?.id||'')||!data.personal)throw Error('Invalid card');s.data=data;s.muted=!!(o.getDialogs()||[]).find(d=>d.id===id)?.muted;applyName(data);render();return true;}catch(e){if(live(s))content.replaceChildren(el('p','contactStatus',errorText(e)),btn('Повторить',()=>open(id)));return false;}}
  function decorate(row){const avatar=row.querySelector('.avatar'),faceNode=row.querySelector('.chatSwipeFace'),main=row.querySelector('.chatMain'),id=row.dataset.conversationId;if(!avatar||!main||!faceNode||!UUID.test(id||'')||row.querySelector('.contactAvatarTrigger'))return;const b=btn('Карточка контакта: '+(row.querySelector('.chatText strong')?.textContent||'Контакт'),()=>open(id),null,'contactAvatarTrigger');b.replaceChildren(avatar);faceNode.insertBefore(b,main);}
  async function refreshHeader(){const i=identity();if(headBusy||!i.sessionUserId||document.hidden||navigator.onLine===false||!['conversation','canvas'].includes(i.screen)||!UUID.test(i.conversationId||'')||page.open)return;headBusy=true;try{const r=await client.rpc('pablicus_contact_card',{p_conversation_id:i.conversationId});const latest=identity();if(r.error||latest.sessionUserId!==i.sessionUserId||latest.sessionGeneration!==i.sessionGeneration||latest.conversationId!==i.conversationId||page.open)return;if(r.data?.kind==='contact')applyName(r.data);}catch{}finally{headBusy=false;}}
  const unsub=controller.subscribe(next=>{if(lastRoute&&(next.sessionGeneration!==lastRoute.sessionGeneration||next.sessionUserId!==lastRoute.sessionUserId)){close(true);urlCache.clear();}else if(page.open&&lastRoute&&next.generation!==lastRoute.generation)close(true);lastRoute=next;if(!page.open)void refreshHeader();});const timer=scope.setInterval(()=>void refreshHeader(),15000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)void refreshHeader();},{signal:lifetime.signal});scope.addEventListener('online',refreshHeader,{signal:lifetime.signal});page.addEventListener('cancel',e=>{e.preventDefault();close();});page.addEventListener('close',()=>{if(!page.open&&state)close(true);});
  return{open,decorate,close,refreshHeader,get opened(){return page.open;},destroy(){close(true);lifetime.abort();unsub();scope.clearInterval(timer);urlCache.clear();page.remove();}};
 }
 scope.PablicusContactCard={create,personalName,profileName,nameOf};
 function boot(){const controller=scope.PablicusController,services=controller?.getServices();if(!services?.client||scope.PablicusContacts)return;const title=document.getElementById('chatTitle'),oldTitle=title?.onclick;const openLibrary=tab=>{oldTitle?.call(title);const b=document.querySelector('.pablicusChatLibrary[open] [data-tab="'+tab+'"]');b?.click();};const card=create({client:services.client,controller,getDialogs:()=>controller.getServices().getDialogs?.()||[],openConversation:d=>controller.getServices().openConversation(d),openLibrary,notify:message=>controller.getServices().notify?.(message)});scope.PablicusContacts=card;if(title){title.setAttribute('aria-label','Открыть карточку собеседника');title.onclick=()=>card.open(controller.state().conversationId);}document.querySelectorAll('.chatCard[data-conversation-id]').forEach(card.decorate);}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})(window);
