/* Account-owned profile photo album. A viewer can read; only the signed-in owner can manage. */
(function(root){
 'use strict';
 const node=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=text;return n;};
 const button=(label,fn,cls='')=>{const b=node('button',cls,label);b.type='button';b.setAttribute('aria-label',label);b.onclick=fn;return b;};
 const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
 function service(client,owner,isCurrent=()=>true){
  const abort=new AbortController(),cache=new Map(),pending=new Map();let dead=false;
  const live=()=>!dead&&isCurrent();
  async function call(name,args){if(!live())throw new DOMException('Closed','AbortError');let q=client.rpc(name,args);if(q.abortSignal)q=q.abortSignal(abort.signal);const r=await q;if(!live())throw new DOMException('Closed','AbortError');if(r.error)throw r.error;return r.data;}
  function safe(path){if(typeof path!=='string'||!path)return false;if(/^https:\/\//i.test(path)){try{const u=new URL(path);return !u.username&&!u.password;}catch{return false;}}return UUID.test(owner)&&path.startsWith(owner+'/')&&!path.includes('..')&&/^[a-z0-9_/-]+\.(jpg|jpeg|png|webp|gif)$/i.test(path);}
  function validate(data){if(data?.owner_id!==owner||!Array.isArray(data.photos)||!Number.isFinite(data.total))throw Error('Invalid album');return{...data,photos:data.photos.filter(p=>p&&safe(p.path))};}
  async function url(path,width=1280){if(!live()||!safe(path))throw Error('Invalid image');if(/^https:\/\//i.test(path))return path;const value=await root.PablicusMediaCache.resolve('profile-media',path,{type:'image',width});if(!live())throw new DOMException('Closed','AbortError');return value;}
  return{live,safe,url,async list(offset=0){return validate(await call('pablicus_profile_photos_list',{p_owner_id:owner,p_offset:offset,p_limit:30}));},async add(paths){return validate(await call('pablicus_profile_photos_add',{p_paths:paths}));},async edit(action,path,avatar){return validate(await call('pablicus_profile_photos_edit',{p_action:action,p_path:path,p_expected_avatar:avatar}));},destroy(){dead=true;abort.abort();cache.clear();pending.clear();}};
 }
 function carousel(host,{client,profile,isCurrent,onActivate=()=>{},onCount=()=>{}}){
  const api=service(client,profile.id,isCurrent),lifetime=new AbortController();let photos=profile.avatar_url?[{path:profile.avatar_url,is_main:true}]:[],total=photos.length,next=null,index=0,loading=false,expanded=false,disposed=false,gesture=null,suppressClick=0;
  const initialFace=host.querySelector('.contactFace');if(initialFace)initialFace.remove();host.replaceChildren();
  const plane=node('div','profilePhotoPlane'),track=node('div','profilePhotoTrack'),controls=node('div','profilePhotoControls'),dots=node('div','profilePhotoDots'),count=node('span','profilePhotoCount'),error=node('div','profilePhotoError');
  const prev=button('Предыдущая фотография',()=>go(-1),'profilePhotoPrev'),after=button('Следующая фотография',()=>go(1),'profilePhotoNext');prev.textContent='‹';after.textContent='›';controls.append(prev,dots,count,after);plane.append(track);host.append(plane,controls,error);host.setAttribute('role','group');host.setAttribute('aria-label','Фотографии профиля');host.tabIndex=0;
  const slides=new Map();
  const live=()=>!disposed&&api.live()&&host.isConnected;
  function paint(){if(!live())return;track.style.transform=`translate3d(${-index*100}%,0,0)`;count.textContent=total?`${index+1} / ${total}`:'';dots.replaceChildren();const start=Math.max(0,Math.min(index-4,total-9));for(let k=start;k<Math.min(total,start+9);k++){const d=node('span',k===index?'selected':'');dots.append(d);}prev.disabled=index===0;after.disabled=index+1>=total;controls.hidden=!expanded||total<2;host.setAttribute('aria-label',total?`Фотографии профиля, ${index+1} из ${total}`:'Фотографии профиля');onCount(total,index);for(let k=expanded?Math.max(0,index-1):index;k<Math.min(photos.length,expanded?index+2:index+1);k++)loadImage(k);}
  function build(){if(!live())return;const existing=new Map([...slides.values()].map(s=>[s.dataset.path,s])),fragment=document.createDocumentFragment();slides.clear();for(const [k,p]of photos.entries()){const slide=existing.get(p.path)||node('div','profilePhotoSlide');slide.dataset.path=p.path;slides.set(k,slide);fragment.append(slide);}track.replaceChildren(fragment);if(!photos.length){const empty=node('div','profilePhotoSlide profilePhotoEmpty',(profile.display_name||profile.username||'?').slice(0,1));track.append(empty);}if(initialFace&&photos[0]?.path===profile.avatar_url&&!initialFace.parentNode){const slide=slides.get(0);slide?.append(initialFace);const img=initialFace.querySelector('img');if(slide&&img?.complete&&img.naturalWidth){slide.dataset.ready='yes';slide.dataset.width='192';}}paint();}
  function loadImage(k,width=expanded?1280:192){
   const slide=slides.get(k),p=photos[k];if(!slide||slide.querySelector('img')&&slide.dataset.ready==='yes'&&Number(slide.dataset.width)>=width)return Promise.resolve();
   if(slide._imageRequest)return slide._imageRequest.then(()=>{if(live()&&slides.get(k)===slide&&slide.dataset.ready==='yes'&&Number(slide.dataset.width)<width)return loadImage(k,width);});
   const task=api.url(p.path,width).then(async url=>{
    if(!live()||slides.get(k)!==slide)return;
    const existing=slide.querySelector('img');if(existing?.src===url&&existing.complete&&existing.naturalWidth){slide.dataset.ready='yes';slide.dataset.width=String(width);return;}
    const img=node('img');img.alt=`Фотография профиля ${k+1}`;img.draggable=false;img.decoding='sync';img.loading='eager';img.referrerPolicy='no-referrer';img.src=url;await img.decode();
    if(live()&&slides.get(k)===slide){slide.replaceChildren(img);slide.dataset.ready='yes';slide.dataset.width=String(width);}
   }).catch(()=>{if(live()&&!slide.querySelector('img')&&k===index)error.replaceChildren(button('Повторить загрузку фото',()=>{error.replaceChildren();loadImage(k,width);}));}).finally(()=>{if(slide._imageRequest===task)slide._imageRequest=null;});
   slide._imageRequest=task;return task;
  }

  async function load(more=false){if(loading||!live())return;loading=true;try{const data=await api.list(more?next||0:0);if(!live())return;const path=photos[index]?.path;photos=more?[...photos,...data.photos.filter(p=>!photos.some(x=>x.path===p.path))]:data.photos;total=data.total;next=data.next_offset;index=Math.max(0,photos.findIndex(p=>p.path===path));if(index>=photos.length)index=0;build();}catch{if(live()&&expanded)error.replaceChildren(button('Обновить фотографии',()=>{error.replaceChildren();load();}));}finally{loading=false;}}
  async function go(delta){if(!live()||!expanded)return;const wanted=index+delta;if(wanted<0||wanted>=total)return;if(wanted>=photos.length&&next!==null)await load(true);if(!live())return;index=Math.max(0,Math.min(wanted,photos.length-1));error.replaceChildren();paint();if(index>=photos.length-3&&next!==null)void load(true);}
  host.addEventListener('pointerdown',e=>{if(!e.isPrimary||e.button!==0||e.target.closest('button'))return;gesture={id:e.pointerId,x:e.clientX,y:e.clientY,axis:null,expanded};},{signal:lifetime.signal});
  host.addEventListener('pointermove',e=>{const g=gesture;if(!g||g.id!==e.pointerId)return;const dx=e.clientX-g.x,dy=e.clientY-g.y;if(Math.max(Math.abs(dx),Math.abs(dy))>2)suppressClick=Date.now()+500;if(!g.expanded)return;if(!g.axis&&Math.max(Math.abs(dx),Math.abs(dy))>9){g.axis=Math.abs(dx)>Math.abs(dy)*1.25?'x':'y';if(g.axis==='x')host.setPointerCapture?.(e.pointerId);}if(g.axis==='x'){if(e.cancelable)e.preventDefault();track.classList.add('is-dragging');const width=host.getBoundingClientRect().width||1;const resistance=index===0&&dx>0||index===total-1&&dx<0?.28:1;track.style.transform=`translate3d(calc(${-index*100}% + ${dx*resistance}px),0,0)`;}},{signal:lifetime.signal});
  function end(e,cancel=false){const g=gesture;gesture=null;if(!g||g.id!==e.pointerId)return;if(cancel||Math.max(Math.abs(e.clientX-g.x),Math.abs(e.clientY-g.y))>2)suppressClick=Date.now()+500;track.classList.remove('is-dragging');if(g.axis==='x'){suppressClick=Date.now()+400;if(!cancel&&Math.abs(e.clientX-g.x)>35)void go(e.clientX<g.x?1:-1);else paint();}}
  host.addEventListener('pointerup',e=>end(e),{signal:lifetime.signal});host.addEventListener('pointercancel',e=>end(e,true),{signal:lifetime.signal});
  host.addEventListener('click',e=>{if(e.target.closest('button')||Date.now()<suppressClick)return;if(!expanded)onActivate();else{const r=host.getBoundingClientRect();void go(e.clientX-r.left<r.width*.35?-1:1);}},{signal:lifetime.signal});
  host.addEventListener('keydown',e=>{if(e.target!==host)return;if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();void go(e.key==='ArrowRight'?1:-1);}else if(['Enter',' '].includes(e.key)){e.preventDefault();onActivate();}},{signal:lifetime.signal});
  build();void load();
  return{plane,controls,get index(){return index;},prepare:()=>loadImage(index,960),setExpanded(value){if(expanded===value)return;expanded=value;host.setAttribute('aria-expanded',String(value));paint();},refresh:()=>load(),destroy(){disposed=true;lifetime.abort();api.destroy();slides.clear();gesture=null;}};
 }
 async function preparePhoto(file){
  if(!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type))throw Error('Выберите фото JPEG, PNG, WebP или GIF.');if(file.size>100*1024*1024)throw Error('Файл больше 100 МБ.');
  const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();if(!img.naturalWidth||img.naturalWidth*img.naturalHeight>50000000)throw Error('Слишком большой размер фотографии.');const scale=Math.min(1,1920/Math.max(img.naturalWidth,img.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.round(img.naturalWidth*scale);canvas.height=Math.round(img.naturalHeight*scale);const c=canvas.getContext('2d');c.fillStyle='#fff';c.fillRect(0,0,canvas.width,canvas.height);c.drawImage(img,0,0,canvas.width,canvas.height);return await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('Не удалось обработать фото.')),'image/jpeg',.91));}finally{URL.revokeObjectURL(url);}
 }
 function openManager({client,getProfile,getIdentity,onProfileChanged,onClose=()=>{}}){
  const identity=getIdentity(),owner=identity.sessionUserId,api=service(client,owner,()=>{const s=getIdentity();return s.sessionUserId===owner&&s.sessionGeneration===identity.sessionGeneration;});let dead=false,busy=false,data=null;
  const dialog=node('dialog','profilePhotosManager'),bar=node('header','profilePhotosManagerBar'),title=node('h1','','Фотографии профиля'),content=node('main','profilePhotosManagerContent'),status=node('p','profilePhotosManagerStatus');status.setAttribute('role','status');
  const exit=button('Закрыть',()=>close(),'profilePhotosClose');exit.textContent='‹';bar.append(exit,title);const pick=node('input');pick.type='file';pick.multiple=true;pick.accept='image/jpeg,image/png,image/webp,image/gif';pick.hidden=true;
  const add=button('Добавить фото',()=>pick.click(),'profilePhotosAdd'),grid=node('div','profilePhotosGrid');content.append(add,pick,status,grid);dialog.append(bar,content);document.body.append(dialog);dialog.showModal();
  function live(){if(!api.live()&&!dead)close(true);return !dead&&api.live()&&dialog.open;}
  function close(force=false){if(busy&&!force)return;if(dead)return;dead=true;api.destroy();dialog.close();dialog.remove();onClose();}
  function changed(next){data=next;const p=getProfile();if(p?.id===owner&&p.avatar_url!==data.avatar_url)onProfileChanged({...p,avatar_url:data.avatar_url});root.dispatchEvent(new CustomEvent('pablicus:profile-photos-changed',{detail:{ownerId:owner}}));}
  function error(e){status.textContent=e?.code==='40001'?'Главное фото изменено на другом устройстве. Обновите альбом.':e?.message?.startsWith('Выберите')||e?.message?.startsWith('Файл')?e.message:'Не удалось загрузить или сохранить фотографии. Повторите.';}
  function lock(value){busy=value;dialog.querySelectorAll('button').forEach(b=>b.disabled=value);}
  async function reload(more=false){if(!live())return;try{const next=await api.list(more?data.next_offset:0);if(!live())return;if(more)next.photos=[...data.photos,...next.photos.filter(p=>!data.photos.some(x=>x.path===p.path))];changed(next);paint();}catch(e){if(live()){error(e);grid.append(button('Обновить альбом',()=>reload()));}}}
  async function mutate(action,p){if(busy||!live())return;if(action==='remove'&&!root.confirm('Убрать фотографию из альбома профиля?'))return;lock(true);status.textContent='';try{const next=await api.edit(action,p.path,data.avatar_url);if(!live())return;changed(next);paint();}catch(e){if(live())error(e);}finally{if(live())lock(false);}}
  function paint(){if(!live()||!data)return;grid.replaceChildren();if(!data.photos.length)grid.append(node('p','','Добавьте первую фотографию.'));for(const p of data.photos){const tile=node('article','profilePhotoTile'),img=node('img');img.alt=p.is_main?'Главное фото':'Фотография профиля';img.loading='lazy';img.referrerPolicy='no-referrer';tile.append(img);api.url(p.path).then(url=>{if(live()&&img.isConnected)img.src=url;}).catch(()=>{});if(p.is_main)tile.append(node('span','profilePhotoPrimary','Главное'));const controls=node('div','profilePhotoTileActions');if(!p.is_main)controls.append(button('Сделать главным',()=>mutate('primary',p)));controls.append(button('Убрать из альбома',()=>mutate('remove',p)));tile.append(controls);grid.append(tile);}if(data.next_offset!==null)grid.append(button('Ещё фотографии',()=>reload(true)));}
  pick.onchange=async()=>{const files=[...pick.files];pick.value='';if(!files.length||!live()||busy)return;if(files.length>20){status.textContent='Выберите до 20 фото за один раз. Затем можно добавить ещё.';return;}lock(true);const paths=[];let submitted=false;try{for(const [i,file]of files.entries()){if(!live())return;status.textContent=`Загрузка ${i+1} из ${files.length}`;const blob=await preparePhoto(file);if(!live())return;const path=owner+'/gallery-'+root.crypto.randomUUID()+'.jpg';const r=await client.storage.from('profile-media').upload(path,blob,{contentType:'image/jpeg',upsert:false});if(r.error)throw r.error;await root.PablicusMediaCache.prepare('profile-media',path);if(!live())return;paths.push(path);}if(!live())return;submitted=true;const next=await api.add(paths);if(!live())return;changed(next);status.textContent='';paint();}catch(e){if(live())error(e);}finally{if(!submitted&&paths.length&&api.live())await client.storage.from('profile-media').remove(paths).catch(()=>{});if(live())lock(false);}};
  dialog.addEventListener('cancel',e=>{e.preventDefault();close();});const unsubscribe=root.PablicusController?.subscribe(()=>{if(!api.live())close(true);});dialog.addEventListener('close',()=>{unsubscribe?.();if(!dead)close(true);},{once:true});void reload();return{close,destroy:()=>close(true)};
 }
 root.PablicusProfilePhotos={service,carousel,openManager,preparePhoto};
})(window);
