/* Personal profile, persistent editing and publications. No account data is stored globally. */
(function(scope){'use strict';
 const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n};
 const button=(label,run,icon,cls='')=>{const b=el('button','youButton '+cls);b.type='button';if(icon)b.append(PablicusMessageMenu.icon(icon));b.append(el('span','',label));b.onclick=run;return b};
 const date=value=>value?new Intl.DateTimeFormat('ru',{day:'numeric',month:'long',year:'numeric'}).format(new Date(value+'T12:00:00')):'';
 function create(o){
  let root=null,uid=null,serial=0,details={},posts=[],albums=[],tab='posts',album='',loaded=false,busy=false,formDirty=false,urls=new Map(),observer=null,editorUrls=[],panel=null,closeQr=null,photoManager=null;
  const sb=o.client,bucket=sb.storage.from('profile-media');
  const viewer=PablicusMediaViewer.create({resolveUrl:item=>resolve(item.path),onError:o.onError});
  const active=t=>root?.isConnected&&uid===o.getUser()?.id&&(t===undefined||t===serial);
  async function result(request){const r=await request;if(r.error)throw r.error;return r.data}
  async function resolve(path){if(!path)return '';if(/^https:\/\//.test(path))return path;const cached=urls.get(path);if(cached&&cached.until>Date.now())return cached.url;const data=await result(bucket.createSignedUrl(path,300));urls.set(path,{url:data.signedUrl,until:Date.now()+240000});return data.signedUrl}
  function fail(error,target){if(!active())return;if(target){target.textContent=error.code==='23505'?'Это имя пользователя уже занято.':error.message?.includes('BIRTHDAY')?'Проверьте дату рождения.':'Не удалось сохранить. Проверьте соединение и повторите.';target.hidden=false}else o.onError(error)}
  function resetMedia(){observer?.disconnect();observer=null;root?.querySelectorAll('video').forEach(v=>{v.pause();v.removeAttribute('src');v.load()});editorUrls.forEach(URL.revokeObjectURL);editorUrls=[]}
  function clear(){closeQr?.();resetMedia();root.replaceChildren();root.className='youPage';formDirty=false;panel=null;PablicusShell.profileTitle('Вы');o.settingsButton.hidden=false;o.backButton.hidden=true}
  function header(title,back=render){document.getElementById('workspace').scrollTop=0;o.settingsButton.hidden=true;o.backButton.hidden=false;o.backButton.onclick=()=>{if(busy)return;if(formDirty){confirmDiscard(back);return}back()};PablicusShell.profileTitle(title)}
  function confirmDiscard(back){const host=o.dialog('Сохранить изменения?');host.append(el('p','','Несохранённые изменения будут потеряны.'),button('Продолжить редактирование',()=>document.getElementById('productDialog').close()),button('Не сохранять',()=>{document.getElementById('productDialog').close();formDirty=false;back()}));}
  function avatar(path,cls='youAvatar'){const face=el('div',cls,(o.getProfile().display_name||o.getProfile().username||'?').slice(0,1).toUpperCase());if(path){const t=serial;resolve(path).then(url=>{if(!active(t)||!face.isConnected)return;const img=el('img');img.alt='Фотография профиля';img.src=url;img.onerror=()=>img.remove();face.replaceChildren(img)}).catch(()=>{})}return face}
  async function load(){const t=++serial;loaded=false;render();try{const data=await Promise.all([result(sb.from('pablicus_profile_details').select('*').eq('owner_id',uid).maybeSingle()),fetchAll('pablicus_profile_posts'),fetchAll('pablicus_profile_albums')]);if(!active(t))return;[details,posts,albums]=data;details||={};loaded=true;if(panel===null)render()}catch(e){if(!active(t)||panel!==null)return;const state=root.querySelector('.youContent');state.replaceChildren(el('p','youMuted','Не удалось загрузить профиль.'),button('Повторить',load));}}
  async function fetchAll(table,owner=uid){const rows=[];for(let from=0;;from+=500){const page=await result(sb.from(table).select('*').eq('owner_id',owner).order('created_at',{ascending:false}).range(from,from+499));rows.push(...page);if(page.length<500)return rows}}
  function infoRow(label,value,action){const row=el('div','youInfoRow');row.append(el('span','youInfoLabel',label));if(action)row.append(button(value||'Добавить',action,null,'youTextAction'));else row.append(el('div','youInfoValue',value));return row}
  function render(){if(!active())return;clear();const p=o.getProfile(),hero=el('section','youHero'),face=button('Открыть фотографию',()=>photos(),null,'youAvatarButton');face.replaceChildren(avatar(p.avatar_url));hero.append(face,el('h1','youName',p.display_name||p.username),el('p','youHandle','@'+p.username));const actions=el('div','youHeroActions');actions.append(button('Изменить',edit,'edit'),button('QR-код',qr,'context'),button('Фотографии',photos,'photo'));hero.append(actions);root.append(hero);
   const content=el('div','youContent');root.append(content);if(!loaded){content.append(el('p','youMuted youLoading','Загружаем профиль…'));return}
   const info=el('section','youInfo');info.setAttribute('aria-label','Сведения профиля');info.append(infoRow('Имя пользователя','@'+p.username,qr));if(details.phone)info.append(infoRow('Мобильный',details.phone));if(details.birthday)info.append(infoRow('День рождения',date(details.birthday)));if(details.bio)info.append(infoRow('О себе',details.bio));if(!details.bio&&!details.phone&&!details.birthday)info.append(infoRow('О себе','Добавить сведения',edit));content.append(info);
   const bar=el('div','youPublicationsHeader'),tabs=el('div','youTabs');tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label','Публикации профиля');for(const[key,label]of [['posts','Публикации'],['archive','Архив']]){const b=button(label,()=>{tab=key;album='';render()},null);b.id='youTab-'+key;b.setAttribute('role','tab');b.setAttribute('aria-selected',String(tab===key));b.tabIndex=tab===key?0:-1;b.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();tab=key==='posts'?'archive':'posts';render();root.querySelector('#youTab-'+tab).focus()}};tabs.append(b)}bar.append(tabs,button('Добавить публикацию',compose,'plus','youIconOnly'));content.append(bar);
   const filters=el('div','youAlbumFilters');const all=button('Все публикации',()=>{album='';render()});all.setAttribute('aria-pressed',String(!album));filters.append(all);for(const a of albums){const b=button(a.title,()=>{album=a.id;render()});b.setAttribute('aria-pressed',String(album===a.id));filters.append(b)}filters.append(button('Альбом',newAlbum,'plus'));content.append(filters);
   const selected=posts.filter(p=>p.archived===(tab==='archive')&&(!album||p.album_id===album));const grid=el('section','youGrid');grid.setAttribute('role','tabpanel');grid.setAttribute('aria-labelledby','youTab-'+tab);content.append(grid);
   if(!selected.length){grid.classList.add('youEmpty');grid.append(PablicusMessageMenu.icon(tab==='archive'?'archive':'photo'),el('h2','',tab==='archive'?'Архив пока пуст':album?'В альбоме пока пусто':'Ваши публикации'),el('p','youMuted',tab==='archive'?'Здесь будут публикации, которые вы уберёте в архив.':'Добавьте фотографии, видео или текст. Они появятся здесь.'),button(tab==='archive'?'К публикациям':'Создать публикацию',tab==='archive'?()=>{tab='posts';render()}:compose,null,'youPrimary'));return}
   observer=new IntersectionObserver(entries=>{for(const e of entries){const v=e.target;if(e.isIntersecting&&!document.hidden&&!viewer.opened)v.play().catch(()=>{});else v.pause()}},{threshold:.25});
   for(const post of selected){const media=post.media?.[0],tile=button(media?'Открыть публикацию':post.body,()=>openPost(post),null,'youTile');tile.dataset.postId=post.id;tile.replaceChildren();if(media){const item=el(media.type==='video'?'video':'img');if(media.type==='video'){item.muted=true;item.defaultMuted=true;item.playsInline=true;item.loop=true;item.preload='metadata'}else{item.alt=post.body||'Фотография публикации';item.loading='lazy'}tile.append(item);const t=serial;resolve(media.path).then(url=>{if(!active(t)||!item.isConnected)return;item.src=url;if(media.type==='video')observer?.observe(item)}).catch(()=>{if(item.isConnected)tile.append(el('span','youMediaError','Повторить загрузку'))});if(media.type==='video'){const marker=el('span','youMediaBadge','Видео');tile.append(marker)}if(post.media.length>1)tile.append(el('span','youMediaCount',String(post.media.length)))}else tile.append(el('p','youTextTile',post.body));grid.append(tile)}
  }
  function statusForm(form){const s=el('p','youError');s.setAttribute('role','alert');s.hidden=true;form.append(s);return s}
  function filePicker(form,label,name){const wrap=el('div','youField'),input=el('input'),summary=el('span','youFileSummary');input.type='file';input.id='you-'+name;input.name=name;input.hidden=true;input.setAttribute('aria-label',label);const choose=button(name==='avatar'?'Выбрать фотографию':'Выбрать фото и видео',()=>input.click(),'photo');summary.setAttribute('role','status');input.addEventListener('change',()=>{const files=[...input.files],photos=files.filter(f=>f.type.startsWith('image/')).length,videos=files.filter(f=>f.type.startsWith('video/')).length;summary.textContent=[photos?'Фото: '+photos:'',videos?'Видео: '+videos:''].filter(Boolean).join(' · ')});wrap.append(el('span','',label),choose,input,summary);form.append(wrap);return input}
  function field(form,label,name,value,type='text',max){if(type==='file')return filePicker(form,label,name);const wrap=el('label','youField'),input=el(type==='textarea'?'textarea':'input');wrap.append(el('span','',label));input.name=name;input.id='you-'+name;if(type!=='textarea')input.type=type;input.value=value||'';if(max)input.maxLength=max;input.oninput=()=>formDirty=true;wrap.append(input);form.append(wrap);return input}
  function submitButton(form,label){const b=button(label,null,null,'youPrimary');b.type='submit';form.append(b);return b}
  async function upload(file){if(!['image/jpeg','image/png','image/webp','image/gif','video/mp4','video/quicktime','video/webm'].includes(file.type))throw Error('Выберите фото JPEG, PNG, WebP, GIF или видео MP4, MOV, WebM.');if(file.size>100*1024*1024)throw Error('Максимальный размер файла — 100 МБ.');const ext={ 'image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/gif':'gif','video/mp4':'mp4','video/quicktime':'mov','video/webm':'webm'}[file.type];const path=uid+'/'+crypto.randomUUID()+'.'+ext;await result(bucket.upload(path,file,{contentType:file.type,upsert:false}));return {type:file.type.startsWith('image/')?'image':'video',path,name:file.name.slice(0,255)}}
  function edit(){if(!loaded)return;clear();panel='edit';header('Профиль');const p=o.getProfile(),form=el('form','youForm');const preview=avatar(p.avatar_url),pick=field(form,'Фотография','avatar','','file');pick.accept='image/jpeg,image/png,image/webp,image/gif';pick.onchange=()=>{formDirty=true;const f=pick.files[0];if(f){const url=URL.createObjectURL(f);editorUrls.push(url);const img=el('img');img.alt='Новая фотография';img.src=url;preview.replaceChildren(img)}};form.prepend(preview);
   const first=field(form,'Имя','firstName',details.first_name||p.display_name||p.username,'text',80);first.required=true;field(form,'Фамилия','lastName',details.last_name,'text',80);const username=field(form,'Имя пользователя','username',p.username,'text',24);username.pattern='[a-z0-9_]{3,24}';username.required=true;username.autocapitalize='none';field(form,'О себе','bio',details.bio,'textarea',500);field(form,'Мобильный','phone',details.phone,'tel',32);const birthday=field(form,'День рождения','birthday',details.birthday,'date');birthday.min='1900-01-01';birthday.max=new Date().toISOString().slice(0,10);form.append(el('p','youMuted','Номер телефона, день рождения и описание пока видны только вам.'));const status=statusForm(form),save=submitButton(form,'Сохранить');root.append(form);
   form.onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;save.disabled=true;status.hidden=true;const t=serial;let added=null,committed=false,submitted=false;try{if(pick.files[0])added=await upload(pick.files[0]);if(!active(t))return;const values=new FormData(form),args={p_first_name:values.get('firstName').trim(),p_last_name:values.get('lastName').trim(),p_username:values.get('username').trim().toLowerCase(),p_bio:values.get('bio').trim(),p_phone:values.get('phone').trim(),p_birthday:values.get('birthday')||null,p_avatar:added?.path||p.avatar_url||null};submitted=true;const saved=await result(sb.rpc('pablicus_save_profile',args));committed=true;if(!active(t))return;o.onProfileChanged(saved);details={first_name:args.p_first_name,last_name:args.p_last_name,bio:args.p_bio,phone:args.p_phone,birthday:args.p_birthday};formDirty=false;render();o.toast('Профиль сохранён')}catch(err){fail(err,status)}finally{if(added&&!committed&&!submitted)await bucket.remove([added.path]);if(t===serial)busy=false;save.disabled=false}};
  }
  function photos(){if(!active()||busy)return;photoManager?.destroy();photoManager=scope.PablicusProfilePhotos.openManager({client:sb,getProfile:o.getProfile,getIdentity:()=>scope.PablicusController.state(),onProfileChanged:p=>o.onProfileChanged(p),onClose:()=>{photoManager=null;if(active())render();}});}
  function settings(){if(!active())return;clear();panel='settings';header('Настройки');o.mountSettings(root)}
  function qr(){closeQr?.();const dialog=el('dialog','youQrDialog'),card=el('div','youQrCard'),focus=document.activeElement;dialog.setAttribute('aria-label','QR-код профиля');dialog.tabIndex=-1;let start=null;const close=()=>{if(dialog.open)dialog.close();dialog.remove();if(closeQr===close)closeQr=null;if(focus?.isConnected)focus.focus({preventScroll:true})};closeQr=close;dialog.addEventListener('cancel',e=>{e.preventDefault();close()});dialog.addEventListener('close',()=>{dialog.remove();if(closeQr===close)closeQr=null});dialog.addEventListener('pointerdown',e=>{if(!e.isPrimary||e.button!==0)return;start={id:e.pointerId,x:e.clientX,y:e.clientY};});dialog.addEventListener('pointermove',e=>{if(start&&e.pointerId===start.id&&Math.hypot(e.clientX-start.x,e.clientY-start.y)>12)dialog.setPointerCapture(e.pointerId)});dialog.addEventListener('pointerup',e=>{const point=start;start=null;if(point&&e.pointerId===point.id&&Math.hypot(e.clientX-point.x,e.clientY-point.y)>65)close()});dialog.addEventListener('pointercancel',()=>start=null);card.append(avatar(o.getProfile().avatar_url),el('h2','',o.getProfile().display_name||o.getProfile().username));const link=PablicusPeople.profileLink(o.getProfile().username),code=qrcodegen.QrCode.encodeText(link,qrcodegen.QrCode.Ecc.MEDIUM),svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 '+(code.size+8)+' '+(code.size+8));svg.setAttribute('role','img');svg.setAttribute('aria-label','QR-код ссылки на профиль');svg.classList.add('youQr');let path='';for(let y=0;y<code.size;y++)for(let x=0;x<code.size;x++)if(code.getModule(x,y))path+='M'+(x+4)+','+(y+4)+'h1v1h-1z';const marks=document.createElementNS(svg.namespaceURI,'path');marks.setAttribute('d',path);marks.setAttribute('fill','#17656b');svg.append(marks);card.append(svg,el('p','youQrUsername','@'+o.getProfile().username),button('Поделиться профилем',()=>o.shareProfile().catch(o.onError),'share','youPrimary'));dialog.append(card);document.body.append(dialog);dialog.showModal();dialog.focus({preventScroll:true})}
  function newAlbum(){const host=o.dialog('Новый альбом'),form=el('form','youForm'),name=field(form,'Название','albumTitle','','text',80);name.required=true;const status=statusForm(form),save=submitButton(form,'Создать');host.append(form);name.focus();form.onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;save.disabled=true;const t=serial;try{const a=await result(sb.from('pablicus_profile_albums').insert({owner_id:uid,title:name.value.trim()}).select().single());if(!active(t))return;albums.unshift(a);album=a.id;document.getElementById('productDialog').close();render()}catch(err){fail(err,status)}finally{if(t===serial)busy=false;save.disabled=false}}}
  function compose(){if(!loaded)return;clear();panel='compose';header('Публикация');const form=el('form','youForm'),text=field(form,'Текст','postBody','','textarea',4000),pick=field(form,'Фото и видео','postFiles','','file');pick.multiple=true;pick.accept='image/jpeg,image/png,image/webp,image/gif,video/mp4,video/quicktime,video/webm';const previews=el('div','youUploadPreviews');form.append(previews);pick.onchange=()=>{formDirty=true;previews.replaceChildren();editorUrls.forEach(URL.revokeObjectURL);editorUrls=[];for(const f of pick.files){const card=el('div','youUploadPreview'),url=URL.createObjectURL(f);editorUrls.push(url);const media=el(f.type.startsWith('video/')?'video':'img');media.src=url;if(media.tagName==='VIDEO'){media.muted=true;media.playsInline=true;media.preload='metadata'}else media.alt='Выбранная фотография';card.append(media);previews.append(card)}};
   const label=el('label','youField','Альбом'),select=el('select');select.name='albumId';select.append(new Option('Без альбома',''));for(const a of albums)select.append(new Option(a.title,a.id));select.value=album;label.append(select);form.append(label,el('p','youMuted','Публикация будет доступна пользователям Пабликуса. До 20 файлов, до 100 МБ каждый.'));const status=statusForm(form),save=submitButton(form,'Опубликовать');root.append(form);
   form.onsubmit=async e=>{e.preventDefault();if(busy)return;const files=[...pick.files];if(!text.value.trim()&&!files.length){status.hidden=false;status.textContent='Добавьте текст, фото или видео.';return}if(files.length>20){status.hidden=false;status.textContent='Можно добавить до 20 файлов за один раз.';return}busy=true;save.disabled=true;status.hidden=true;const t=serial,media=[];let committed=false,submitted=false;try{for(const file of files){save.querySelector('span').textContent='Загрузка '+(media.length+1)+' из '+files.length;media.push(await upload(file));if(!active(t))return}submitted=true;const post=await result(sb.from('pablicus_profile_posts').insert({owner_id:uid,body:text.value.trim(),media,album_id:select.value||null,archived:false}).select().single());committed=true;if(!active(t))return;posts.unshift(post);tab='posts';album=post.album_id||'';formDirty=false;render();o.toast('Публикация добавлена')}catch(err){fail(err,status);if(status.isConnected&&(err.message?.startsWith('Выберите')||err.message?.startsWith('Максимальный')))status.textContent=err.message}finally{if(!committed&&!submitted&&media.length)await bucket.remove(media.map(m=>m.path));if(t===serial)busy=false;save.disabled=false;save.querySelector('span').textContent='Опубликовать'}};
  }
  function openPost(post){clear();panel='post';header('Публикация');observer=new IntersectionObserver(entries=>{for(const e of entries){if(e.isIntersecting&&!document.hidden&&!viewer.opened)e.target.play().catch(()=>{});else e.target.pause()}},{threshold:.25});const article=el('article','youPost');article.append(el('p','youMuted',new Date(post.created_at).toLocaleDateString('ru',{day:'numeric',month:'long',year:'numeric'})));if(post.body)article.append(el('p','youPostText',post.body));for(const [i,item]of post.media.entries()){const b=button('Открыть '+(item.type==='video'?'видео':'фото'),()=>viewer.open(post.media,i),null,'youPostMedia');b.replaceChildren();const media=el(item.type==='video'?'video':'img');if(item.type==='video'){media.muted=true;media.playsInline=true;media.loop=true;media.preload='metadata'}else media.alt=post.body||'Фотография публикации';const t=serial;resolve(item.path).then(url=>{if(active(t)&&media.isConnected){media.src=url;if(item.type==='video')observer?.observe(media)}}).catch(o.onError);b.append(media);article.append(b)}const actions=el('div','youPostActions'),status=statusForm(article);const archive=button(post.archived?'Вернуть в публикации':'В архив',async()=>{if(busy)return;busy=true;archive.disabled=true;const t=serial;try{await result(sb.from('pablicus_profile_posts').update({archived:!post.archived}).eq('id',post.id).eq('owner_id',uid));if(active(t)){post.archived=!post.archived;render();o.toast(post.archived?'Публикация в архиве':'Публикация восстановлена')}}catch(e){fail(e,status)}finally{if(t===serial)busy=false;archive.disabled=false}},'archive');const label=el('label','youField','Альбом'),select=el('select');select.append(new Option('Без альбома',''));for(const a of albums)select.append(new Option(a.title,a.id));select.value=post.album_id||'';select.onchange=async()=>{const previous=post.album_id,t=serial;select.disabled=true;try{await result(sb.from('pablicus_profile_posts').update({album_id:select.value||null}).eq('id',post.id).eq('owner_id',uid));if(active(t))post.album_id=select.value||null}catch(e){select.value=previous||'';fail(e,status)}finally{select.disabled=false}};label.append(select);actions.append(label,archive);article.append(actions);root.append(article)}
  function syncVideos(){if(!active())return;root.querySelectorAll('video').forEach(v=>{const r=v.getBoundingClientRect();if(!document.hidden&&!viewer.opened&&r.bottom>60&&r.top<innerHeight-80)v.play().catch(()=>{});else v.pause()})}
  document.addEventListener('visibilitychange',syncVideos);document.addEventListener('pablicus:media-viewer',syncVideos);
  return {mount(host){if(root?.isConnected&&uid===o.getUser()?.id)return;uid=o.getUser().id;root=el('section','youPage');host.append(root);tab='posts';album='';details={};posts=[];albums=[];urls.clear();o.settingsButton.onclick=settings;load()},mounted:host=>root?.isConnected&&root.parentNode===host&&uid===o.getUser()?.id,destroy(){++serial;photoManager?.destroy();photoManager=null;closeQr?.();viewer.close();resetMedia();root?.remove();root=null;uid=null;urls.clear();busy=false;formDirty=false;loaded=false;panel=null;o.settingsButton.hidden=true;o.backButton.hidden=true}};
 }
 scope.PablicusProfilePage=Object.freeze({create});
})(window);
