(function(g){'use strict';if(g.PablicusStoriesCore)return;
const C=g.PablicusController,S=()=>C?.getServices?.(),UUID=/^[0-9a-f]{8}-[0-9a-f-]{27}$/i,$=(q,r=document)=>r.querySelector(q),$$=(q,r=document)=>[...r.querySelectorAll(q)],E=(t,c,x)=>{const n=document.createElement(t);if(c)n.className=c;if(x!=null)n.textContent=x;return n};
const cache=new Map();let shelf=null,compact=null,raf=0,scrollBound=null;
const state=()=>C?.state?.()||{},own=()=>S()?.getProfile?.()||null,notify=x=>S()?.notify?.(x);
function active(id){return $$('[data-story-owner="'+CSS.escape(id)+'"]').some(n=>n.dataset.pablicusStoryRing==='active')}
function source(id){return $$('[data-story-owner="'+CSS.escape(id)+'"]').find(n=>n.querySelector('img'))||$$('[data-story-owner="'+CSS.escape(id)+'"]')[0]}
function picture(id){const n=source(id);return n?.querySelector('img')?.currentSrc||n?.querySelector('img')?.src||''}
function row(id){return $$('.chatCard[data-conversation-id]').find(r=>r.querySelector('[data-story-owner="'+CSS.escape(id)+'"]'))}
function title(id){if(id===own()?.id)return 'Моя история';const r=row(id);return r?.querySelector('.chatText strong')?.textContent?.trim()||r?.querySelector('strong')?.textContent?.trim()||'Сторис'}
const conversation=id=>row(id)?.dataset.conversationId||null;
function avatar(id,cls='storyShelfAvatar'){const a=E('span',cls);a.dataset.storyOwner=id;a.dataset.pablicusStoryRing=active(id)?'active':'none';const u=picture(id);if(u){const im=new Image;im.alt='';im.src=u;a.append(im)}else a.textContent=(title(id)[0]||'?').toUpperCase();return a}
function owners(){const out=[],me=own()?.id;if(UUID.test(me||''))out.push(me);$$('#screenContent [data-story-owner][data-pablicus-story-ring="active"]').forEach(n=>{const id=n.dataset.storyOwner;if(UUID.test(id||'')&&!out.includes(id))out.push(id)});return out}
async function feed(owner){const hit=cache.get(owner);if(hit&&Date.now()-hit.at<8000)return hit.items;const r=await S().client.rpc('pablicus_story_feed',{p_owners:[owner]});if(r.error)throw r.error;const now=Date.parse(r.data?.server_now)||Date.now(),items=(r.data?.stories||[]).filter(x=>x.owner_id===owner&&UUID.test(x.id||'')&&Date.parse(x.expires_at)>now);cache.set(owner,{at:Date.now(),items});return items}
async function media(story){if(!story?.media?.path)return null;const key='m:'+story.id,hit=cache.get(key);if(hit&&Date.now()-hit.at<240000)return hit.blob;const r=await S().client.storage.from('pablicus-story-media').download(story.media.path);if(r.error)throw r.error;cache.set(key,{at:Date.now(),blob:r.data});return r.data}
function open(id,trigger){if(id===own()?.id&&!active(id)){g.PablicusAvatarStoriesUI?.compose?.();return}g.PablicusStoriesViewer?.open?.(id,conversation(id),trigger)}
function item(id,me=false,compactMode=false){const b=E('button',compactMode?'storyCompactItem':'storyShelfItem');b.type='button';b.dataset.owner=id;b.setAttribute('aria-label',me?'Моя история':title(id));b.append(avatar(id,compactMode?'storyCompactAvatar':'storyShelfAvatar'));if(!compactMode)b.append(E('span','storyShelfLabel',me?'Моя история':title(id)));b.onclick=e=>{e.preventDefault();open(id,b)};return b}
function collapse(v){if(!shelf)return;shelf.classList.toggle('collapsed',v);shelf.classList.toggle('expanded',!v);compact?.classList.toggle('visible',v)}
function scroll(){if(shelf&&scrollBound)collapse(scrollBound.scrollTop>54)}
function profile(){const id=own()?.id;$('#storyOwnView')?.remove();if(!UUID.test(id||''))return;$$('.youMotionPage .pablicusStoryProfile,.youAvatarButton.pablicusStoryProfile').forEach(n=>n.dataset.storyOwner=id)}
function shelfUI(){const st=state(),home=$('#home'),ws=$('#workspace');if(!home||!ws)return;const on=st.screen==='home'&&st.section==='chats';home.classList.toggle('storiesV3Chats',on);$('#storyOwnView')?.remove();if(!on){shelf?.remove();shelf=null;compact?.remove();compact=null;return}const top=$('.homeHeader',home);if(!compact&&top){compact=E('div','storyShelfCompact');compact.id='storyShelfCompact';top.append(compact)}if(!shelf){shelf=E('section','storyShelfV3 expanded');shelf.id='storyShelfV3';shelf.innerHTML='<div class="storyShelfRailV3"></div><div class="storyShelfSearch"></div>';ws.prepend(shelf);let y=0;shelf.addEventListener('pointerdown',e=>y=e.clientY,{passive:true});shelf.addEventListener('pointerup',e=>{const d=e.clientY-y;if(Math.abs(d)>24)collapse(d<0)})}const search=$('#searchChats');if(search){search.hidden=false;$('.storyShelfSearch',shelf)?.append(search)}$('#chatUpperToggle')?.setAttribute('hidden','');$('#chatUpperPanel')?.setAttribute('hidden','');$('#chatFilters')?.setAttribute('hidden','');const ids=owners(),sig=ids.map(x=>x+active(x)+picture(x)).join('|'),rail=$('.storyShelfRailV3',shelf);if(rail&&rail.dataset.sig!==sig){rail.dataset.sig=sig;rail.replaceChildren(...ids.map((id,i)=>item(id,i===0&&id===own()?.id,false)));compact?.replaceChildren(...ids.slice(0,4).map((id,i)=>item(id,i===0&&id===own()?.id,true)));ids.slice(0,4).filter(active).forEach(id=>void feed(id).then(x=>x[0]?.media?.path?media(x[0]):null).catch(()=>{}))}if(scrollBound!==ws){scrollBound?.removeEventListener?.('scroll',scroll);scrollBound=ws;ws.addEventListener('scroll',scroll,{passive:true})}scroll()}
function intercept(e){const t=e.target.closest?.('.youMotionPage .pablicusStoryProfile,.youAvatarButton.pablicusStoryProfile,.contactAvatarTrigger,#conversationAvatar');if(!t)return;const id=t.dataset.storyOwner||t.querySelector?.('[data-story-owner]')?.dataset.storyOwner;if(!UUID.test(id||''))return;if(t.matches?.('.youMotionPage .pablicusStoryProfile,.youAvatarButton.pablicusStoryProfile')&&!active(id))return;if(!active(id))return;e.preventDefault();e.stopImmediatePropagation();open(id,t)}
function tick(){raf=0;profile();shelfUI()}function go(){if(!raf)raf=requestAnimationFrame(tick)}
new MutationObserver(go).observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['data-pablicus-story-ring','class','hidden']});g.addEventListener('click',intercept,true);C?.subscribe?.(go);document.addEventListener('visibilitychange',()=>{if(!document.hidden){cache.clear();go()}},{passive:true});g.PablicusStoriesCore={C,S,UUID,$,$$,E,state,own,notify,active,picture,title,conversation,avatar,feed,media,cache,refresh:go};go();
})(window);