import {initialize} from './assets/ui/app.mjs';
const vv=new EventTarget();Object.assign(vv,{height:innerHeight,width:innerWidth,offsetTop:0,scale:1});Object.defineProperty(window,'visualViewport',{value:vv});
const turns=Array.from({length:25},(_,i)=>({id:'admin-'+i,user_text:'Задание '+i,reply:'Ответ администратора '+i,created_at:new Date(2026,8,23,10,i).toISOString(),answered_at:new Date(2026,8,23,10,i).toISOString(),status:'completed'}));
window.SekkesS2={updateReady:false,busy:false,voiceActive:false,saveDraft(){},ownerRequest:async p=>p==='status'?{owner:true,active:true}:{turns,media:[],documents:[],costs:{},budget_cap_usd:1},loadEarlier:async()=>{},chatMedia:async()=>{},sendText:async()=>{const input=document.querySelector('#draft');SekkesUI.render('user',input.value,{id:'sent-'+Date.now()});input.value='';}};
initialize();const pause=()=>new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('Paint frames stalled')),20000);let left=4;function next(){if(--left)requestAnimationFrame(next);else{clearTimeout(timeout);resolve();}}requestAnimationFrame(next);});const wait=async fn=>{for(let i=0;i<60&&!fn();i++)await pause();if(!fn())throw Error('Timeout')};
await wait(()=>document.querySelector('.messages'));SekkesUI.account({id:'synthetic-qa'});SekkesUI.status('');
const results=document.querySelector('#testResults');
document.querySelector('#runCheck').onclick=async()=>{const checks=[];const check=(name,value)=>{checks.push([name,!!value]);results.textContent=checks.map(([n,v])=>(v?'PASS ':'FAIL ')+n).join('\n')};try{
 const list=document.querySelector('.messages'),input=document.querySelector('#draft'),form=document.querySelector('#composer');
 const gap=()=>list.scrollHeight-list.clientHeight-list.scrollTop;
 for(let i=0;i<40;i++)SekkesUI.render(i%2?'ai':'user','Текст сообщения '+i+'\nПроверка устойчивого положения.',{id:'m'+i,at:new Date(2026,8,23,11,i).toISOString()});await pause();
 check('initial last message',gap()<3);check('history reaches both screen edges',Math.abs(list.getBoundingClientRect().top-document.querySelector('#shell').getBoundingClientRect().top)<2&&Math.abs(list.getBoundingClientRect().bottom-document.querySelector('#shell').getBoundingClientRect().bottom)<2);check('last message above composer',list.lastElementChild.getBoundingClientRect().bottom<=form.getBoundingClientRect().top);
 for(let i=0;i<3;i++){input.focus({preventScroll:true});Object.assign(vv,{height:420,offsetTop:250});vv.dispatchEvent(new Event('resize'));await pause();check('keyboard retains last '+i+' gap='+gap()+' follow='+list.timelineController.following,gap()<3);check('keyboard last visible '+i,list.lastElementChild.getBoundingClientRect().bottom<=form.getBoundingClientRect().top);input.blur();Object.assign(vv,{height:innerHeight,offsetTop:0});vv.dispatchEvent(new Event('resize'));await pause();check('close retains last '+i+' gap='+gap(),gap()<3)}
 const media=document.createElement('div');media.style.height='180px';list.children[35].append(media);await pause();media.style.height='360px';await pause();check('late media retains last gap='+gap(),gap()<3);
 list.dispatchEvent(new WheelEvent('wheel',{deltaY:-400}));list.scrollTop=Math.max(0,list.scrollTop-500);list.dispatchEvent(new Event('scroll'));await pause();
 const anchor=[...list.children].find(n=>n.getBoundingClientRect().bottom>list.getBoundingClientRect().top+1),before=anchor.getBoundingClientRect().top-list.getBoundingClientRect().top;
 SekkesUI.render('ai','Новый ответ во время чтения',{id:'incoming'});await pause();check('reading behind composer',list.getBoundingClientRect().bottom>form.getBoundingClientRect().bottom);check('incoming preserves reading',Math.abs(anchor.getBoundingClientRect().top-list.getBoundingClientRect().top-before)<2);
 const samples=[],nativeScroll=list.scrollTo.bind(list);let commands=0,sampling=true;list.scrollTo=(options)=>{if(options.behavior==='smooth')commands++;return nativeScroll(options)};
 const sample=()=>{samples.push(list.scrollTop);if(sampling)requestAnimationFrame(sample)};requestAnimationFrame(sample);
 document.querySelector('.chat-bottom').click();document.querySelector('.chat-bottom').click();await wait(()=>gap()<3);await pause();await pause();sampling=false;
 check('one smooth command despite repeated click',commands===1);check('native descent never reverses',samples.every((v,i)=>!i||v>=samples[i-1]-3));check('arrival remains stable',samples.slice(-4).every(v=>Math.abs(v-list.scrollTop)<3));
 media.style.height='450px';await pause();check('single jump survives media resize gap='+gap()+' follow='+list.timelineController.following,gap()<3);
 const same=list.querySelector('[data-message-id="m20"]');SekkesUI.history([{id:'m20',speaker:'user',text:'Текст сообщения 20\nПроверка устойчивого положения.',at:new Date(2026,8,23,11,20).toISOString()}]);await pause();check('unchanged node retained',same===list.querySelector('[data-message-id="m20"]'));
 const n=list.lastElementChild;n.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,cancelable:true}));await pause();check('message menu',!!document.querySelector('.message-context-menu'));document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));
 location.hash='admin';await wait(()=>document.querySelector('.owner-messages'));await pause();const admin=document.querySelector('.owner-messages');check('admin opens at end',admin.scrollHeight-admin.clientHeight-admin.scrollTop<3);check('admin history reaches both edges',Math.abs(admin.getBoundingClientRect().top-document.querySelector('#shell').getBoundingClientRect().top)<2&&Math.abs(admin.getBoundingClientRect().bottom-document.querySelector('#shell').getBoundingClientRect().bottom)<2);check('admin last visible',admin.lastElementChild.getBoundingClientRect().bottom<=document.querySelector('.owner-composer').getBoundingClientRect().top);
 const ainput=document.querySelector('.owner-input');ainput.focus({preventScroll:true});Object.assign(vv,{height:420,offsetTop:0});vv.dispatchEvent(new Event('resize'));await pause();check('admin keyboard end',admin.scrollHeight-admin.clientHeight-admin.scrollTop<3);ainput.blur();Object.assign(vv,{height:innerHeight,offsetTop:0});vv.dispatchEvent(new Event('resize'));await pause();
 location.hash='home';await wait(()=>document.querySelector('.messages'));await pause();check('return home retains end',gap()<3);check('draft focusable',!input.disabled);
 for(let i=0;i<2;i++){for(const [w,h] of [[844,390],[390,844]]){frameElement.style.width=w+'px';frameElement.style.height=h+'px';await pause();Object.assign(vv,{width:innerWidth,height:innerHeight,offsetTop:0});dispatchEvent(new Event('orientationchange'));vv.dispatchEvent(new Event('resize'));await pause();check('rotate '+i+' '+w+' end',gap()<3);const menu=document.querySelector('#menuTrigger'),r=menu.getBoundingClientRect();check('rotate '+i+' '+w+' menu hit target',menu.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)));menu.click();await pause();check('rotate '+i+' '+w+' menu works',menu.getAttribute('aria-expanded')==='true');menu.click();}}
 input.focus({preventScroll:true});Object.assign(vv,{height:420,offsetTop:250});vv.dispatchEvent(new Event('resize'));await pause();check('focus after rotation',document.activeElement===input&&gap()<3&&list.lastElementChild.getBoundingClientRect().bottom<=form.getBoundingClientRect().top);input.blur();Object.assign(vv,{height:innerHeight,offsetTop:0});vv.dispatchEvent(new Event('resize'));

 }catch(e){check('exception '+e.message,false);console.error(e)}
};
