import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync(new URL('../../vision-talk/pablicus/personal-invites.js',import.meta.url),'utf8'),token='a'.repeat(64),key='pablicus:pending-invite';
class Element{constructor(tag){this.tagName=tag;this.dataset={};this.children=[];this.isConnected=false;this.open=false;this.textContent='';this.listeners={};}append(...nodes){for(const n of nodes){n.parent=this;n.isConnected=true;this.children.push(n);}}replaceChildren(...nodes){this.children=[];this.append(...nodes);}setAttribute(k,v){this[k]=v;}addEventListener(k,v){this.listeners[k]=v;}showModal(){this.open=true;}close(){this.open=false;}focus(){}remove(){this.parent.children=this.parent.children.filter(n=>n!==this);}querySelectorAll(tag){return this.children.flatMap(n=>[...(n.tagName===tag?[n]:[]),...n.querySelectorAll(tag)]);}}
function fixture({hash='',user:initial={id:'owner'},reply,clock,stored,share,clipboard}={}){let user=initial;const calls=[],storage=new Map(stored||[]),body=new Element('body'),listeners={},location={hash,pathname:'/vision-talk/pablicus/',search:''},document={body,createElement:t=>new Element(t),activeElement:null};const window={document,URL,location,history:{state:null,replaceState(_s,_t,path){calls.push({scrub:path});location.hash='';}},sessionStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},navigator:{share,clipboard:{writeText:clipboard||async function(url){calls.push({copied:url});}}},addEventListener:(event,callback)=>listeners[event]=callback,PablicusInvite:{canonical:()=> 'https://example.test/vision-talk/pablicus/',share:async()=>{calls.push('generic');return true;}}};vm.runInNewContext(source,{window,document,Date,setTimeout:clock||setTimeout,clearTimeout});const who={id:'sender',display_name:'Fixture Sender',username:'sender'};const api=window.PablicusPersonalInvites.create({client:{rpc:async(name,args)=>{calls.push(args);if(reply)return reply(args);if(args.p_action==='list')return{data:{ok:true,invites:[]}};if(args.p_action==='create')return{data:{ok:true,token,invite:{id:'invite'}}};if(args.p_action==='inspect')return{data:{ok:true,invite:{status:'active',inviter:who}}};if(args.p_action==='accept')return{data:{ok:true,inviter:who}};return{data:{ok:true}};}},getUser:()=>user,onOpen:(_p,guard)=>{assert.equal(guard.isCurrent(),true);calls.push('open');}});api.mount(body);const all=()=>body.querySelectorAll('dialog').flatMap(p=>[p,...p.querySelectorAll('button'),...p.querySelectorAll('p'),...p.querySelectorAll('input')]);return{api,calls,storage,location,listeners,setUser:value=>user=value,button:t=>all().find(n=>n.tagName==='button'&&n.textContent===t),panel:()=>all().find(n=>n.tagName==='dialog'),status:()=>all().find(n=>n.role==='status'),rpc:()=>calls.filter(n=>n?.p_action),window};}
const tick=()=>new Promise(r=>setTimeout(r,0));
test('capture strips capability synchronously and never includes it in clean URL',()=>{const f=fixture({hash:'#invite='+token,user:null});assert.equal(f.location.hash,'');assert.equal(f.calls[0].scrub,'/vision-talk/pablicus/');assert.equal(JSON.parse(f.storage.get(key)).token,token);assert.equal(f.rpc().length,0);});
test('invalid duplicate and malformed invitation fragments are removed and never stored',()=>{for(const hash of ['#invite=bad','#invite='+token+'&invite='+token,'#invite='+token.toUpperCase(),'#invite']){const f=fixture({hash});assert.equal(f.storage.has(key),false);assert.equal(f.location.hash,'');}});
test('noninvite auth fragments untouched',()=>{const f=fixture({hash:'#access_token=authcallback'});assert.equal(f.location.hash,'#access_token=authcallback');assert.equal(f.calls.length,0);});
test('guest bootstrap preserves pending invite until approved login',async()=>{const f=fixture({hash:'#invite='+token,user:null});f.api.clear({preserveUnbound:true});await f.api.ready();assert.equal(f.rpc().length,0);f.setUser({id:'owner'});await f.api.ready();assert.deepEqual(f.rpc().map(x=>x.p_action),['inspect']);assert.ok(f.button('Принять приглашение'));assert.equal(f.calls.includes('open'),false);});
test('redirect reload restores same-tab pending within TTL',async()=>{const a=fixture({hash:'#invite='+token,user:null});const f=fixture({stored:[...a.storage]});await f.api.ready();assert.equal(f.rpc()[0].p_action,'inspect');});
test('expired local pending is discarded',async()=>{const f=fixture({stored:[[key,JSON.stringify({token,until:Date.now()-1,owner:null})]]});await f.api.ready();assert.equal(f.rpc().length,0);assert.equal(f.storage.has(key),false);});
test('explicit clear removes pending even beforelogin',()=>{const f=fixture({hash:'#invite='+token,user:null});f.api.clear();assert.equal(f.storage.has(key),false);});
test('bound pending never crosses account switch/reload',async()=>{const f=fixture({stored:[[key,JSON.stringify({token,until:Date.now()+10000,owner:'other'})]]});await f.api.ready();assert.equal(f.rpc().length,0);assert.equal(f.storage.has(key),false);});
test('same-account refresh never reinspects or accepts',async()=>{const f=fixture({hash:'#invite='+token});await f.api.ready();await f.api.ready();assert.deepEqual(f.rpc().map(x=>x.p_action),['inspect']);});
test('accept and opening chat require separate explicit actions',async()=>{const f=fixture({hash:'#invite='+token});await f.api.ready();await f.button('Принять приглашение').onclick();assert.deepEqual(f.rpc().map(x=>x.p_action),['inspect','accept']);assert.equal(f.storage.has(key),false);assert.equal(f.calls.includes('open'),false);await f.button('Открыть чат').onclick();assert.equal(f.calls.at(-1),'open');assert.equal(f.panel().open,false);});
test('same-receiver replay offers chat without another accept',async()=>{const f=fixture({hash:'#invite='+token,reply:()=>({data:{ok:true,invite:{status:'accepted',inviter:{id:'sender',display_name:'Sender'}}}})});await f.api.ready();assert.ok(f.button('Открыть чат'));assert.equal(f.button('Принять приглашение'),undefined);assert.equal(f.rpc().length,1);});
test('expired revoked and other-receiver replay are unavailable without identity leak',async()=>{const f=fixture({hash:'#invite='+token,reply:()=>({data:{ok:false,error:'unavailable',detail:'SECRET'}})});await f.api.ready();assert.match(f.status().textContent,/недоступно/);assert.ok(!f.status().textContent.includes('SECRET'));assert.equal(f.button('Принять приглашение'),undefined);});
test('create never shares until second user gesture; native cancel retains URL',async()=>{let shared=0;const f=fixture({share:async()=>{shared++;const e=Error();e.name='AbortError';throw e;}});await f.api.open();await f.button('Создать приглашение').onclick();assert.equal(shared,0);await f.button('Отправить приглашение').onclick();assert.equal(shared,1);assert.match(f.status().textContent,/отменена/);await f.button('Копировать ссылку').onclick();assert.equal(f.calls.at(-1).copied,'https://example.test/vision-talk/pablicus/#invite='+token);assert.equal(f.storage.has(key),false);});
test('unsupported sharing copies capability only on gesture',async()=>{const f=fixture();await f.api.open();await f.button('Создать приглашение').onclick();await f.button('Отправить приглашение').onclick();assert.equal(f.calls.at(-1).copied.endsWith('#invite='+token),true);});
test('copy failure exposes manual field without leaking into errors',async()=>{const f=fixture({clipboard:async()=>{throw Error(token);}});await f.api.open();await f.button('Создать приглашение').onclick();await f.button('Копировать ссылку').onclick();assert.match(f.status().textContent,/поле ссылки/);assert.ok(!f.status().textContent.includes(token));});
test('closing forgets generated token and reopening uses list without reconstruction',async()=>{const f=fixture();await f.api.open();await f.button('Создать приглашение').onclick();f.api.close();await f.api.open();assert.equal(f.button('Копировать ссылку'),undefined);assert.deepEqual(f.rpc().map(x=>x.p_action),['list','create','list']);});
test('late create after logout never exposes token',async()=>{let finish;const f=fixture({reply:args=>args.p_action==='create'?new Promise(r=>finish=r):{data:{ok:true,invites:[]}}});await f.api.open();const p=f.button('Создать приглашение').onclick();f.setUser(null);f.api.clear();finish({data:{ok:true,token}});await p;assert.equal(f.panel().open,false);assert.equal(f.button('Копировать ссылку'),undefined);});
test('late inspect and accept after account switch never expose previous sender',async()=>{for(const action of ['inspect','accept']){let finish;const f=fixture({hash:'#invite='+token,reply:args=>args.p_action===action?new Promise(r=>finish=r):{data:{ok:true,invite:{status:'active',inviter:{id:'sender'}}}}});let p=f.api.ready();if(action==='accept'){await p;p=f.button('Принять приглашение').onclick();}f.setUser({id:'other'});finish({data:{ok:true,invite:{status:'active',inviter:{id:'sender'}},inviter:{id:'sender'}}});await p;assert.equal(f.panel().open,false);assert.equal(f.storage.has(key),false);}});
test('duplicate clicks during create are singleflight',async()=>{let finish;const f=fixture({reply:args=>args.p_action==='create'?new Promise(r=>finish=r):{data:{ok:true,invites:[]}}});await f.api.open();const b=f.button('Создать приглашение');const p=b.onclick();b.onclick();assert.equal(f.rpc().filter(x=>x.p_action==='create').length,1);finish({data:{ok:true,token}});await p;});
test('create timeout never retries and describes list/revoke recovery',async()=>{let fire;const f=fixture({reply:args=>args.p_action==='create'?new Promise(()=>{}):{data:{ok:true,invites:[]}},clock:fn=>{fire=fn;return 123;}});await f.api.open();const p=f.button('Создать приглашение').onclick();fire();await p;assert.equal(f.rpc().filter(x=>x.p_action==='create').length,1);assert.match(f.status().textContent,/список приглашений/);assert.equal(f.button('Обновить список').disabled,false);});
test('list permits explicit revoke and displays no recipient',async()=>{const f=fixture({reply:args=>({data:args.p_action==='list'?{ok:true,invites:[{id:'one',status:'active',created_at:'2026-09-19T00:00:00Z'}]}:{ok:true}})});await f.api.open();await f.button('Отозвать').onclick();assert.equal(f.rpc().at(-1).p_input.id,'one');assert.match(f.status().textContent,/отозвано/);});
test('generic F01 sharing remains callable',async()=>{const f=fixture();await f.api.open();await f.button('Поделиться обычной ссылкой Pablicus').onclick();assert.equal(f.calls.at(-1),'generic');});
test('cancel receiving invite deletes pending capability',async()=>{const f=fixture({hash:'#invite='+token});await f.api.ready();f.button('Не сейчас').onclick();assert.equal(f.storage.has(key),false);assert.equal(f.panel().open,false);});

test('failed native sharing after account change never falls back to old-token clipboard',async()=>{let reject;const f=fixture({share:()=>new Promise((_r,j)=>reject=j)});await f.api.open();await f.button('Создать приглашение').onclick();const p=f.button('Отправить приглашение').onclick();f.setUser({id:'other'});f.api.clear();reject(Error('share failed'));await p;assert.equal(f.calls.some(x=>x?.copied),false);});
test('list pagination exposes older revocable invitations',async()=>{const f=fixture({reply:args=>({data:args.p_input.before_id?{ok:true,invites:[{id:'older',status:'accepted'}],next_cursor:null}:{ok:true,invites:[],next_cursor:'cursor'}})});await f.api.open();await f.button('Показать ещё').onclick();assert.equal(f.rpc().at(-1).p_input.before_id,'cursor');assert.ok(f.button('Отозвать'));assert.equal(f.button('Показать ещё'),undefined);});
