import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync(new URL('../../vision-talk/pablicus/joined-notifications.js',import.meta.url),'utf8');
const uid='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',eid='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',pid='cccccccc-cccc-4ccc-8ccc-cccccccccccc',key='pablicus:pending-joined';
class Element{constructor(tag){this.tagName=tag;this.dataset={};this.children=[];this.isConnected=false;this.open=false;this.textContent='';this.listeners={};}append(...nodes){for(const n of nodes){n.parent=this;n.isConnected=true;this.children.push(n);}}replaceChildren(...nodes){this.children=[];this.append(...nodes);}setAttribute(k,v){this[k]=v;}addEventListener(k,v){this.listeners[k]=v;}showModal(){this.open=true;}close(){this.open=false;}focus(){}remove(){this.parent.children=this.parent.children.filter(n=>n!==this);}querySelectorAll(tag){return this.children.flatMap(n=>[...(n.tagName===tag?[n]:[]),...n.querySelectorAll(tag)]);}}
function fixture({query='',user:initial={id:uid},reply,clock,stored}={}){let user=initial;const calls=[],storage=new Map(stored||[]),body=new Element('body'),listeners={},location={href:'https://example.test/app/'+query},document={body,createElement:t=>new Element(t),activeElement:null};const state={ok:true,revision:0,receive_enabled:false,announce_enabled:false,announce_available:true,feature_enabled:true};const window={document,URL,location,history:{state:null,replaceState(_s,_t,path){calls.push({scrub:path});location.href='https://example.test'+path;}},sessionStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},navigator:{serviceWorker:{addEventListener:(event,cb)=>listeners[event]=cb}}};vm.runInNewContext(source,{window,document,Date,setTimeout:clock||setTimeout,clearTimeout});const api=window.PablicusJoined.create({getUser:()=>user,client:{rpc:async(name,args)=>{calls.push(args);if(reply)return reply(args);return{data:args.p_action==='event'?{ok:true,event:{id:eid,person:{id:pid,display_name:'Fixture Person'}}}:state};}},onOpen:(person,guard)=>{assert.ok(guard.isCurrent());calls.push({opened:person.id});}});api.mount(body);const all=tag=>body.querySelectorAll(tag);return{api,calls,storage,listeners,window,state,setUser:u=>user=u,button:t=>all('button').find(n=>n.textContent===t),panel:()=>all('dialog')[0],status:()=>all('p').find(n=>n.role==='status'),inputs:()=>all('input'),rpc:()=>calls.filter(c=>c.p_action)};}
const query='?joined='+eid+'&recipient='+uid;
test('captures and scrubs URL before auth, preserves unrelated hash/query',()=>{const f=fixture({query:query+'&x=1#auth',user:null});assert.equal(f.window.location.href,'https://example.test/app/?x=1#auth');assert.equal(f.rpc().length,0);assert.equal(JSON.parse(f.storage.get(key)).recipient,uid);});
test('malformed and duplicate URL values never persist',()=>{for(const q of ['?joined=bad&recipient='+uid,query+'&joined='+eid]){const f=fixture({query:q});assert.equal(f.storage.has(key),false);}});
test('initial guest clear preserves recipient-bound notification until login',async()=>{const f=fixture({query,user:null});f.api.clear({preservePending:true});await f.api.ready();assert.equal(f.rpc().length,0);f.setUser({id:uid});await f.api.ready();assert.equal(f.rpc()[0].p_action,'event');assert.ok(f.button('Открыть чат'));});
test('wrong account cannot query or expose event',async()=>{const f=fixture({query,user:{id:pid}});await f.api.ready();assert.equal(f.rpc().length,0);assert.equal(f.storage.has(key),false);});
test('event click needs explicit chat opening',async()=>{const f=fixture({query});await f.api.ready();assert.ok(!f.calls.some(c=>c.opened));await f.button('Открыть чат').onclick();assert.equal(f.calls.at(-1).opened,pid);assert.equal(f.panel().open,false);});
test('refresh same account does not duplicate event reads',async()=>{const f=fixture({query});await f.api.ready();await f.api.ready();assert.equal(f.rpc().length,1);});
test('settings read never writes default opt-ins',async()=>{const f=fixture();await f.api.open();assert.deepEqual(f.rpc().map(c=>c.p_action),['state']);assert.deepEqual(f.inputs().map(x=>x.checked),[false,false]);});
test('explicit save sends both choices and server revision',async()=>{const f=fixture();await f.api.open();f.inputs()[0].checked=true;await f.button('Сохранить').onclick();assert.deepEqual(JSON.parse(JSON.stringify(f.rpc()[1])),{p_action:'preferences',p_input:{expected_revision:0,receive_enabled:true,announce_enabled:false}});});
test('ineligible announce disabled but existing opt-in can be switched off',async()=>{for(const enabled of [false,true]){const f=fixture({reply:()=>({data:{ok:true,revision:1,announce_available:false,announce_enabled:enabled}})});await f.api.open();assert.equal(f.inputs()[1].disabled,!enabled);}});
test('conflict requires explicit state refresh and never retries write',async()=>{const f=fixture({reply:a=>({data:a.p_action==='preferences'?{ok:false,error:'revision_conflict'}:{ok:true,revision:3}})});await f.api.open();await f.button('Сохранить').onclick();assert.match(f.status().textContent,/другом устройстве/);assert.equal(f.rpc().length,2);});
test('late settings response after logout cannot display controls',async()=>{let finish;const f=fixture({reply:()=>new Promise(r=>finish=r)});const p=f.api.open();f.setUser(null);f.api.clear();finish({data:{ok:true,revision:0}});await p;assert.equal(f.panel().open,false);assert.equal(f.button('Сохранить'),undefined);});
test('late event after account switch discards identity',async()=>{let finish;const f=fixture({query,reply:()=>new Promise(r=>finish=r)});const p=f.api.ready();f.setUser({id:pid});finish({data:{ok:true,event:{person:{id:pid,display_name:'SECRET'}}}});await p;assert.equal(f.panel().open,false);assert.equal(f.status().textContent,'');});
test('singleflight prevents duplicate preferences write',async()=>{let finish;const f=fixture({reply:a=>a.p_action==='preferences'?new Promise(r=>finish=r):{data:{ok:true,revision:0}}});await f.api.open();const b=f.button('Сохранить'),p=b.onclick();b.onclick();assert.equal(f.rpc().filter(c=>c.p_action==='preferences').length,1);finish({data:{ok:true,revision:1}});await p;});
test('timeout releases controls without autoretry',async()=>{let fire;const f=fixture({reply:()=>new Promise(()=>{}),clock:cb=>(fire=cb,1)});const p=f.api.open();fire();await p;assert.match(f.status().textContent,/ответ/);assert.equal(f.button('Обновить').disabled,false);assert.equal(f.rpc().length,1);});
test('unavailable event does not display any identity from error payload',async()=>{const f=fixture({query,reply:()=>({data:{ok:false,error:'unavailable',person:{display_name:'SECRET'}}})});await f.api.ready();assert.match(f.status().textContent,/недоступно/);assert.equal(f.button('Открыть чат'),undefined);});
test('expired pending state removed',async()=>{const f=fixture({stored:[[key,JSON.stringify({event:eid,recipient:uid,until:Date.now()-1})]]});await f.api.ready();assert.equal(f.rpc().length,0);assert.equal(f.storage.has(key),false);});
test('SW wrong recipient ignored; current recipient queries server',async()=>{const f=fixture();f.listeners.message({data:{type:'PABLICUS_JOINED_OPEN',eventId:eid,recipientId:pid}});assert.equal(f.rpc().length,0);f.listeners.message({data:{type:'PABLICUS_JOINED_OPEN',eventId:eid,recipientId:uid}});await new Promise(r=>setTimeout(r,0));assert.equal(f.rpc()[0].p_action,'event');});
test('explicit logout clears pending even before auth',()=>{const f=fixture({query,user:null});f.api.clear();assert.equal(f.storage.has(key),false);});

test('ordinary conversation push recipient stays bound in URL',()=>{const q='?conversation='+eid+'&recipient='+uid;const f=fixture({query:q});assert.equal(f.window.location.href,'https://example.test/app/'+q);assert.equal(f.storage.has(key),false);});
test('late response after timed-out event cannot expose sender',async()=>{let fire,finish;const f=fixture({query,clock:cb=>(fire=cb,1),reply:()=>new Promise(r=>finish=r)});const p=f.api.ready();fire();await p;finish({data:{ok:true,event:{person:{id:pid,display_name:'LATE'}}}});await Promise.resolve();assert.equal(f.button('Открыть чат'),undefined);assert.match(f.status().textContent,/ответ/);});
test('hostile display name stays literal text content',async()=>{const f=fixture({query,reply:()=>({data:{ok:true,event:{person:{id:pid,display_name:'<img src=x onerror=alert(1)>'}}}})});await f.api.ready();assert.equal(f.status().textContent,'<img src=x onerror=alert(1)>');assert.equal(f.status().children.length,0);});
