import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {webcrypto} from 'node:crypto';
const source=fs.readFileSync('vision-talk/pablicus/calls-webrtc.js','utf8'),controller=fs.readFileSync('vision-talk/pablicus/calls-client.js','utf8');
const uid='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',cid='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',peer='cccccccc-cccc-4ccc-8ccc-cccccccccccc',id='dddddddd-dddd-4ddd-8ddd-dddddddddddd';
const flush=async()=>{for(let i=0;i<15;i++)await Promise.resolve();};
function mediaFixture({defer=false,fail=''}={}){let stopped=0,asked=0,resolve;const tracks=[{kind:'audio',enabled:true,stop(){stopped++;}}],stream={getTracks:()=>tracks,getAudioTracks:()=>tracks,getVideoTracks:()=>[]},pcs=[],signals=[];class PC{constructor(){if(fail==='constructor')throw Error('fail');pcs.push(this);}addTrack(){if(fail==='addTrack')throw Error('fail');}async createOffer(){if(fail==='offer')throw Error('fail');return{type:'offer',sdp:'fixture'};}async setLocalDescription(d){this.localDescription={...d,toJSON:()=>d};}async setRemoteDescription(d){if(fail==='remote')throw Error('fail');this.remoteDescription=d;}async createAnswer(){return{type:'answer',sdp:'fixture'};}async addIceCandidate(c){this.ice=[...(this.ice||[]),c];}setConfiguration(c){this.config=c;}close(){this.closed=true;}}
const window={navigator:{mediaDevices:{getUserMedia(){asked++;return defer?new Promise(r=>resolve=r):Promise.resolve(stream);}}},RTCPeerConnection:PC};vm.runInNewContext(source,{window});const api=window.PablicusCalls.create({onSignal:s=>{signals.push(s);if(fail==='signal')throw Error('fail');}});return{api,stream,pcs,signals,get stopped(){return stopped;},get asked(){return asked;},resolve:()=>resolve(stream)};}
test('cancel during media request stops late tracks without peer creation',async()=>{const f=mediaFixture({defer:true});const p=f.api.start();await flush();f.api.hangup();f.resolve();await assert.rejects(p);assert.equal(f.stopped,1);assert.equal(f.pcs.length,0);});
test('ICE buffered before SDP does not request media',async()=>{const f=mediaFixture();await f.api.accept({type:'candidate',candidate:{candidate:'early'}});assert.equal(f.asked,0);await f.api.accept({type:'description',description:{type:'offer',sdp:'fixture'}});assert.equal(f.pcs[0].ice.length,1);assert.equal(f.signals[0].description.type,'answer');f.api.hangup();});
for(const failure of ['constructor','addTrack','offer','signal'])test('media stops after '+failure+' failure',async()=>{const f=mediaFixture({fail:failure});await assert.rejects(f.api.start());await flush();assert.equal(f.stopped,1);assert.equal(f.api.active,false);});
test('remote SDP failure stops acquired media',async()=>{const f=mediaFixture({fail:'remote'});await assert.rejects(f.api.accept({type:'description',description:{type:'offer',sdp:'fixture'}}));assert.equal(f.stopped,1);});
test('caller restart bounded; receiver cannot originate restart',async()=>{const f=mediaFixture();await f.api.start();assert.equal(await f.api.restart(),true);assert.equal(await f.api.restart(),true);assert.equal(await f.api.restart(),false);f.api.hangup();const receiver=mediaFixture();await receiver.api.accept({type:'description',description:{type:'offer',sdp:'fixture'}});assert.equal(await receiver.api.restart(),false);receiver.api.hangup();});
test('hangup idempotent and mute reflects actual track',async()=>{const f=mediaFixture();await f.api.start();f.api.setMuted(true);assert.equal(f.stream.getTracks()[0].enabled,false);f.api.hangup();f.api.hangup();assert.equal(f.stopped,1);});
function fixture({enabled=true,incoming=false,query='',reply}={}){let user={id:uid},serverCall=incoming?{id,conversation_id:cid,caller_id:peer,callee_id:uid,status:'ringing',generation:1,media:'audio',expires_at:new Date(Date.now()+45000).toISOString()}:null,mediaAsked=0,stopped=0;const requests=[],timers=new Map();let ti=0;const events={},instances=[];const window={crypto:webcrypto,URL,location:{href:'https://example.test/'+query},history:{replaceState(_s,_t,path){window.location.href='https://example.test'+path;}},atob:s=>Buffer.from(s,'base64').toString(),setTimeout:(fn,ms)=>{timers.set(++ti,{fn,ms});return ti;},clearTimeout:i=>timers.delete(i),addEventListener:(n,f)=>events[n]=f,navigator:{serviceWorker:{addEventListener:(n,f)=>events[n]=f}},PablicusCalls:{create(o){const inst={async start(){mediaAsked++;await o.onSignal({type:'description',description:{type:'offer',sdp:'fixture'}});},async accept(){mediaAsked++;},hangup(){stopped++;},configure(){},restart:async()=>true,setMuted(){},setVideo(){},o};instances.push(inst);return inst;}}};const client={rpc:async(_name,args)=>{requests.push(args);if(reply){const r=await reply(args);if(r)return r;}const a=args.p_action,p=args.p_input;if(a==='state')return{data:{ok:true,available:enabled,reason:enabled?null:'disabled',calls:serverCall?[serverCall]:[]}};if(a==='create'){serverCall={id,conversation_id:cid,caller_id:uid,callee_id:peer,caller_device:p.device_id,status:'ringing',generation:1,media:p.media,expires_at:new Date(Date.now()+45000).toISOString()};return{data:{ok:true,call:serverCall}};}if(a==='ice')return{data:{ok:true,iceServers:[{urls:['turn:fixture.invalid'],username:'fixture',credential:'fixture'}],iceTransportPolicy:'relay',expires_at:new Date(Date.now()+300000).toISOString()}};if(a==='accept'){serverCall={...serverCall,status:'connecting',callee_device:p.device_id};return{data:{ok:true,call:serverCall}};}if(a==='sync')return{data:{ok:true,call:serverCall,signals:[],cursor:0}};if(['end','cancel','reject'].includes(a))serverCall=null;return{data:{ok:true}};}};vm.runInNewContext(controller,{window,URL,setTimeout:window.setTimeout,clearTimeout:window.clearTimeout,Date});const api=window.PablicusCallClient.create({client,getUser:()=>user});return{api,window,requests,timers,events,instances,setUser:u=>user=u,setCall:c=>serverCall=c,get mediaAsked(){return mediaAsked;},get stopped(){return stopped;},async ready(){api.ready({access_token:'fixture'});await flush();}};}
test('disabled gate never creates call or asks microphone',async()=>{const f=fixture({enabled:false});await f.ready();assert.equal(await f.api.start(cid),false);assert.equal(f.mediaAsked,0);assert.equal(f.requests.some(r=>r.p_action==='create'),false);f.api.clear();});
test('incoming server event never acquires microphone automatically',async()=>{const f=fixture({incoming:true});await f.ready();assert.equal(f.api.snapshot().phase,'incoming');assert.equal(f.mediaAsked,0);assert.equal(f.instances.length,0);await f.api.accept();assert.equal(f.instances.length,1);assert.equal(f.requests.filter(r=>r.p_action==='accept').length,1);f.api.clear();});
test('outgoing offer only after backend create and relay authorization',async()=>{const f=fixture();await f.ready();await f.api.start(cid);const actions=f.requests.map(r=>r.p_action);assert.ok(actions.indexOf('create')<actions.indexOf('ice'));assert.ok(actions.indexOf('ice')<actions.indexOf('signal'));assert.equal(f.mediaAsked,1);await f.api.end();assert.equal(f.stopped,1);assert.ok(f.requests.some(r=>r.p_action==='cancel'));f.api.clear();});
test('same account token refresh preserves active media and device',async()=>{const f=fixture();await f.ready();await f.api.start(cid);f.api.ready({access_token:'refreshed'});await flush();assert.equal(f.stopped,0);assert.equal(f.api.snapshot().call.id,id);f.api.clear();});
test('account switch tears down current media',async()=>{const f=fixture();await f.ready();await f.api.start(cid);f.setUser({id:peer});f.api.ready({access_token:'other'});assert.equal(f.stopped,1);assert.equal(f.api.snapshot().call,null);f.api.clear();});
test('late create after cancellation cannot resurrect call',async()=>{let finish;const f=fixture({reply:args=>args.p_action==='create'?new Promise(r=>finish=r):null});await f.ready();const p=f.api.start(cid);await flush();await f.api.end();finish({data:{ok:true,call:{id,generation:1,status:'ringing'}}});assert.equal(await p,false);assert.equal(f.mediaAsked,0);assert.equal(f.api.snapshot().call,null);f.api.clear();});
test('missing TURN credentials blocks microphone even after create',async()=>{const f=fixture({reply:a=>a.p_action==='ice'?{data:{ok:true,iceServers:[],iceTransportPolicy:'all'}}:null});await f.ready();assert.equal(await f.api.start(cid),false);assert.equal(f.mediaAsked,0);f.api.clear();});
test('legacy conversation recipient URL preserved',()=>{const f=fixture({query:'?conversation='+cid+'&recipient='+uid});assert.match(f.window.location.href,/recipient=/);});
test('call URL scrubbed before authentication',()=>{const f=fixture({query:'?call='+id+'&recipient='+uid});assert.equal(f.window.location.href,'https://example.test/');assert.equal(f.requests.length,0);});
test('wrong-recipient call wakeup ignored',async()=>{const f=fixture();await f.ready();const count=f.requests.length;f.events.message({data:{type:'PABLICUS_CALL_OPEN',callId:id,recipientId:peer}});assert.equal(f.requests.length,count);f.api.clear();});
test('repeated network failures do not extend first failure deadline',async()=>{let failing=false;const f=fixture({reply:a=>failing&&a.p_action==='state'?{error:{message:'offline'}}:null});await f.ready();await f.api.start(cid);await flush();failing=true;await f.api.reconcile();const timer=[...f.timers].find(([,x])=>x.ms===20000);assert.ok(timer);await f.api.reconcile();assert.ok(f.timers.has(timer[0]));timer[1].fn();await flush();assert.equal(f.api.snapshot().call,null);assert.equal(f.stopped,1);f.api.clear();});
test('server revocation immediately stops media',async()=>{let revoked=false;const f=fixture({reply:a=>revoked&&a.p_action==='state'?{data:{ok:false,error:'not_allowed'}}:null});await f.ready();await f.api.start(cid);await flush();revoked=true;await f.api.reconcile();assert.equal(f.api.snapshot().call,null);assert.equal(f.stopped,1);f.api.clear();});
