/* Functional lifecycle tests. Browser/auth/network boundaries are synthetic; no live Push is sent. */
import vm from 'node:vm';
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {webcrypto,createECDH} from 'node:crypto';
const code=readFileSync(process.env.R2_CLIENT_SOURCE||'vision-talk/pablicus/push-notifications.js','utf8');
const A='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',B='cccccccc-cccc-4ccc-8ccc-cccccccccccc',I='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
const ecdh=createECDH('prime256v1');ecdh.generateKeys();const KEY=new Uint8Array(ecdh.getPublicKey()),PUBLIC=Buffer.from(KEY).toString('base64url');
const flush=async()=>{for(let i=0;i<200;i++)await Promise.resolve();};
function deferred(){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};}
function events(){const listeners=new Map();return{addEventListener(n,fn){if(!listeners.has(n))listeners.set(n,new Set());listeners.get(n).add(fn);},removeEventListener(n,fn){listeners.get(n)?.delete(fn);},dispatch(n,data={}){for(const fn of listeners.get(n)||[])fn(data);},size(){return[...listeners.values()].reduce((n,s)=>n+s.size,0);}};}
function fixture(o={}){
 let user=A,sessionToken='USER_JWT_A',now=1750000000000,timerId=0,currentSub,seqEndpoint=0;
 const lockSet=o.lockSet||new Set();const timers=new Map(),store=o.store||new Map([['pablicus:push-owner',A]]),calls=[],worker=[],unsubscribed=[],counts={permissionRequests:0,subscribes:0,gets:0,locks:0};
 function subscription(key=KEY,expired=false){const endpoint='https://fixture.invalid/push/'+(++seqEndpoint);const s={endpoint,options:{applicationServerKey:key.buffer},expirationTime:expired?now-1:null,toJSON:()=>({endpoint,keys:{p256dh:'SYNTHETIC',auth:'SYNTHETIC'}}),unsubscribe:async()=>{unsubscribed.push(endpoint);if(currentSub===s)currentSub=null;return true;}};return s;}
 currentSub=o.lost?null:subscription(o.key||KEY,o.expired);
 const initial=currentSub;
 const reg={scope:'https://app.invalid/pablicus/',active:{postMessage(msg,ports){worker.push(msg);ports[0].postMessage({ok:true});}},getNotifications:async()=>[],pushManager:{getSubscription:async()=>{counts.gets++;return currentSub;},subscribe:async opts=>{counts.subscribes++;assert.equal(opts.userVisibleOnly,true);assert.deepEqual([...opts.applicationServerKey],[...KEY]);if(o.subscribeGate)await o.subscribeGate.promise;currentSub=subscription();return currentSub;}}};
 class Channel{constructor(){const a={},b={};a.close=b.close=()=>{};a.postMessage=data=>queueMicrotask(()=>b.onmessage?.({data}));b.postMessage=data=>queueMicrotask(()=>a.onmessage?.({data}));this.port1=a;this.port2=b;}}
 class Clock extends Date{constructor(...args){super(...(args.length?args:[now]));}static now(){return now;}}
 const win=events(),doc={hidden:false,...events()},sw={getRegistration:async()=>o.wrongScope?{...reg,scope:'https://app.invalid/'}:reg,ready:Promise.resolve(reg),...events()};
 const context={URL,MessageChannel:Channel,AbortController,Uint8Array,Promise,atob,crypto:webcrypto,Date:Clock,Math,PushManager:{},Notification:{permission:o.permission||'granted',requestPermission:async()=>{counts.permissionRequests++;context.Notification.permission='granted';return'granted';}},location:{href:reg.scope},isSecureContext:true,matchMedia:()=>({matches:true}),localStorage:{getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)},PablicusBuild:{id:o.noBuild?null:'git:'+'f'.repeat(40)},navigator:{userAgent:'iPhone',onLine:o.online!==false,serviceWorker:sw,locks:{request:async(n,opts,cb)=>{if(typeof opts==='function'){cb=opts;opts={};}counts.locks++;if(lockSet.has(n)||(opts.ifAvailable&&o.lockUnavailable))return cb(null);lockSet.add(n);try{return await cb({name:n});}finally{lockSet.delete(n);}}}},document:doc,...win,setTimeout:(fn,ms)=>{const id=++timerId;timers.set(id,{fn,at:now+ms});return id;},clearTimeout:id=>timers.delete(id),fetch:async(url,opt)=>{const body=opt.body?JSON.parse(opt.body):null;calls.push({...opt,body});if(o.networkGate)await o.networkGate.promise;if(o.failNetwork)throw Error('SYNTHETIC_OFFLINE');if(opt.method==='GET')return Response.json({publicKey:PUBLIC});if(body?.action==='revoke'&&o.revokeGate)await o.revokeGate.promise;if(body?.action==='reconcile'&&o.reconcileGate)await o.reconcileGate.promise;return Response.json(body?.action==='status'?{ok:true,banner_visibility:'unknown'}:{ok:true,installation_id:I,tracking:'ready'});}};
 if(o.disabled)store.set('pablicus:r2:consent:'+A,'disabled');if(o.noConsent)store.clear();
 context.window=context;vm.runInNewContext(code,context);
 const client=context.PablicusPush.create({projectUrl:'https://fixture.supabase.co',apiKey:'PUBLIC_FIXTURE',getUserId:()=>user,getSession:async()=>({access_token:sessionToken,user:{id:user}})});
 async function advance(ms){now+=ms;const due=[...timers].filter(([,v])=>v.at<=now);for(const[id,v]of due){if(timers.delete(id))v.fn();}await flush();}
 return{client,calls,worker,store,counts,session:()=>({access_token:sessionToken,user:{id:user}}),unsubscribed,initial,context,doc,sw,reg,subscription,advance,locked:()=>[...lockSet].some(x=>!x.endsWith(':sequence')),sub:()=>currentSub,setSub:v=>{currentSub=v;},setUser:v=>{user=v;sessionToken=v===A?'USER_JWT_A':'USER_JWT_B';},setToken:v=>{sessionToken=v;},dispatch:win.dispatch,dispose:()=>client.destroy()};
}
const checks=[];async function test(name,fn){if(process.env.R2_TEST_FILTER&&!name.includes(process.env.R2_TEST_FILTER))return;try{await fn();checks.push({name,passed:true});console.log('PASS '+name);}catch(e){checks.push({name,passed:false,error:e.stack});console.error('FAIL '+name+': '+e.message);}}
const registered=f=>f.calls.filter(x=>x.body?.action==='reconcile');
await test('healthy subscription reconciles once; burst lifecycle events preserve endpoint',async()=>{const f=fixture();try{const work=f.client.refresh();f.dispatch('pageshow');f.dispatch('online');f.doc.dispatch('visibilitychange');f.sw.dispatch('controllerchange');await work;await flush();assert.equal(f.client.enabled,true);assert.equal(registered(f).length,1);assert.equal(f.counts.subscribes,0);assert.equal(f.unsubscribed.length,0);assert.equal(f.counts.permissionRequests,0);assert.equal(registered(f)[0].body.subscription.endpoint,f.initial.endpoint);}finally{f.dispose();}});
await test('missing permitted subscription is repaired without permission prompt',async()=>{const f=fixture({lost:true});try{await f.client.refresh();assert.equal(f.counts.subscribes,1);assert.equal(f.client.enabled,true);assert.equal(f.counts.permissionRequests,0);assert.equal(registered(f).length,1);}finally{f.dispose();}});
for(const variant of ['mismatch','expired'])await test(variant+' subscription is replaced exactly once',async()=>{const key=new Uint8Array(KEY);key[10]^=1;const f=fixture(variant==='mismatch'?{key}:{expired:true});try{await f.client.refresh();assert.deepEqual(f.unsubscribed,[f.initial.endpoint]);assert.equal(f.counts.subscribes,1);assert.equal(registered(f).length,1);assert.notEqual(registered(f)[0].body.subscription.endpoint,f.initial.endpoint);await f.client.refresh();assert.equal(f.counts.subscribes,1);}finally{f.dispose();}});
await test('offline to online starts deferred repair',async()=>{const f=fixture({online:false,lost:true});try{await f.client.refresh();assert.equal(f.calls.length,0);f.context.navigator.onLine=true;f.dispatch('online');await f.client.refresh();assert.equal(f.client.enabled,true);assert.equal(f.counts.subscribes,1);}finally{f.dispose();}});
for(const settings of [{permission:'default'},{permission:'denied'},{disabled:true},{noConsent:true}])await test('automatic repair respects '+JSON.stringify(settings),async()=>{const f=fixture({...settings,lost:true});try{await f.client.refresh();f.dispatch('pageshow');f.sw.dispatch('controllerchange');await flush();assert.equal(f.calls.length,0);assert.equal(f.counts.subscribes,0);assert.equal(f.counts.permissionRequests,0);assert.equal(f.client.enabled,false);}finally{f.dispose();}});
await test('explicit disable persists app consent across OS granted and lifecycle',async()=>{const f=fixture();try{await f.client.refresh();await f.client.disable();const n=f.calls.length;f.dispatch('pageshow');await f.client.refresh();assert.equal(f.store.get('pablicus:r2:consent:'+A),'disabled');assert.equal(f.client.enabled,false);assert.equal(f.calls.length,n);assert.equal(f.worker.at(-1).recipientId,null);assert.equal(f.calls.filter(x=>x.body?.action==='revoke').length,1);}finally{f.dispose();}});
await test('token refresh preserves account identity, subscription and throttle',async()=>{const f=fixture();try{await f.client.refresh();const clientId=registered(f)[0].body.installation.client_id;f.setToken('USER_JWT_A_REFRESHED');await f.client.refresh();assert.equal(registered(f).length,1);await f.advance(60001);await f.client.refresh();assert.equal(registered(f).length,2);assert.equal(registered(f)[1].body.installation.client_id,clientId);assert.equal(registered(f)[1].headers.Authorization,'Bearer USER_JWT_A_REFRESHED');assert.equal(f.unsubscribed.length,0);assert.equal(f.counts.subscribes,0);}finally{f.dispose();}});
await test('timeout fences late registration response and schedules bounded retry',async()=>{const gate=deferred(),f=fixture({reconcileGate:gate});try{const p=f.client.refresh();await flush();assert.equal(registered(f).length,1);await f.advance(12000);await p;gate.resolve();await flush();assert.equal(f.client.enabled,false);assert.equal(f.store.get('pablicus:r2:consent:'+A),undefined);const n=f.calls.length;f.dispatch('online');await flush();assert.equal(f.calls.length,n);await f.advance(3000);await flush();assert.equal(f.client.enabled,true);}finally{gate.resolve();f.dispose();}});
await test('unabortable subscribe retains lock after deadline and cleans late endpoint',async()=>{const gate=deferred(),f=fixture({lost:true,subscribeGate:gate});try{const p=f.client.refresh();await flush();assert.equal(f.locked(),true);await f.advance(36000);await p;assert.equal(f.locked(),true);await f.advance(3000);f.dispatch('pageshow');await flush();assert.equal(f.counts.subscribes,1);gate.resolve();await flush();assert.equal(f.unsubscribed.length,1);assert.equal(registered(f).length,0);assert.equal(f.locked(),false);}finally{gate.resolve();f.dispose();}});
await test('logout revokes generation and ignores late network success',async()=>{const gate=deferred(),f=fixture({reconcileGate:gate});try{const p=f.client.refresh();await flush();await f.client.signOut();f.setUser(null);gate.resolve();await p;assert.equal(f.client.enabled,false);assert.equal(f.worker.at(-1).recipientId,null);assert.equal(f.sub(),null);assert.equal(f.store.get('pablicus:push-owner'),undefined);assert.equal(f.calls.filter(x=>x.body?.action==='revoke').length,1);const seq=registered(f)[0].body.operation_seq;assert.ok(f.calls.find(x=>x.body?.action==='revoke').body.operation_seq>seq);}finally{gate.resolve();f.dispose();}});
await test('account switch cleanup prevents late old bind; new consent required',async()=>{const gate=deferred(),f=fixture({lost:true,subscribeGate:gate});try{const p=f.client.refresh();await flush();await f.client.clear();f.setUser(B);gate.resolve();await p;await f.client.refresh();assert.equal(registered(f).length,0);assert.equal(f.sub(),null);assert.equal(f.client.enabled,false);assert.equal(f.worker.at(-1).recipientId,null);assert.equal(f.store.get('pablicus:push-owner'),undefined);}finally{gate.resolve();f.dispose();}});
await test('second device keeps separate stable installation and only local revocation',async()=>{const f=fixture(),g=fixture();try{await f.client.refresh();await g.client.refresh();const id=registered(f)[0].body.installation.client_id,other=registered(g)[0].body.installation.client_id;assert.notEqual(id,other);await f.client.signOut();assert.equal(f.calls.find(x=>x.body?.action==='revoke').body.installation.client_id,id);assert.equal(g.client.enabled,true);assert.equal(g.unsubscribed.length,0);}finally{f.dispose();g.dispose();}});
await test('wrong service worker scope is rejected before any registration',async()=>{const f=fixture({wrongScope:true});try{await f.client.refresh();assert.equal(f.calls.length,0);assert.equal(f.counts.subscribes,0);assert.equal(f.worker.length,0);}finally{f.dispose();}});
await test('worker binding contains only type and recipient, never session JWT',async()=>{const f=fixture();try{await f.client.refresh();await f.client.signOut();for(const m of f.worker){assert.deepEqual(Object.keys(m).sort(),['recipientId','type']);assert.equal(m.type,'PABLICUS_PUSH_BIND');}assert.ok(f.worker.length>=2);}finally{f.dispose();}});
await test('busy other tab never creates concurrent subscription and retries',async()=>{const opts={lockUnavailable:true,lost:true},f=fixture(opts);try{await f.client.refresh();assert.equal(f.counts.subscribes,0);opts.lockUnavailable=false;await f.advance(2500);await flush();assert.equal(f.counts.subscribes,1);assert.equal(f.client.enabled,true);}finally{f.dispose();}});
await test('destroy removes lifecycle callbacks and prevents further work',async()=>{const f=fixture();await f.client.refresh();f.dispose();const n=f.calls.length;f.dispatch('pageshow');f.dispatch('online');f.doc.dispatch('visibilitychange');f.sw.dispatch('controllerchange');await f.advance(120000);assert.equal(f.calls.length,n);assert.equal(f.doc.size(),0);assert.equal(f.sw.size(),0);});
await test('logout blocks lifecycle until revoke completes',async()=>{const gate=deferred(),f=fixture({revokeGate:gate});try{await f.client.refresh();const p=f.client.signOut();await flush();const n=registered(f).length;f.dispatch('online');f.dispatch('pageshow');await f.client.refresh();await f.advance(120000);assert.equal(registered(f).length,n);assert.equal(f.worker.at(-1).recipientId,null);gate.resolve();await p;assert.equal(f.client.enabled,false);}finally{gate.resolve();f.dispose();}});
await test('logout pause propagates to another tab before owner removal',async()=>{const store=new Map([['pablicus:push-owner',A],['pablicus:r2:consent:'+A,'enabled']]),f=fixture({store}),g=fixture({store});try{await f.client.refresh();await g.client.refresh();await f.client.signOut();const n=registered(g).length;g.dispatch('storage',{key:'pablicus:r2:paused:'+A});g.dispatch('storage',{key:'pablicus:push-owner'});await g.client.refresh();await g.advance(120000);assert.equal(registered(g).length,n);assert.equal(g.client.enabled,false);}finally{f.dispose();g.dispose();}});
await test('enable supersedes in-flight cancelled operation and completes repair',async()=>{const gate=deferred(),f=fixture({lost:true,subscribeGate:gate});try{const p=f.client.refresh();await flush();const enabled=f.client.enable();await flush();gate.resolve();await p;await enabled;assert.equal(f.client.enabled,true);assert.equal(f.counts.subscribes,2);assert.equal(registered(f).length,1);}finally{gate.resolve();f.dispose();}});
await test('restored new account reruns after old in-flight operation',async()=>{const gate=deferred(),f=fixture({lost:true,subscribeGate:gate});try{const p=f.client.refresh();await flush();await f.client.clear();f.setUser(B);f.store.set('pablicus:r2:consent:'+B,'enabled');const restored=f.client.sessionRestored();gate.resolve();await p;await restored;await f.advance(100);await f.client.refresh();assert.equal(f.client.enabled,true);assert.equal(registered(f).length,1);assert.equal(registered(f)[0].headers.Authorization,'Bearer USER_JWT_B');assert.equal(f.worker.at(-1).recipientId,B);}finally{gate.resolve();f.dispose();}});
await test('disabled device can explicitly enable again',async()=>{const f=fixture();try{await f.client.refresh();await f.client.disable();await f.client.enable();assert.equal(f.client.enabled,true);assert.equal(f.store.get('pablicus:r2:consent:'+A),'enabled');}finally{f.dispose();}});
await test('disable then reload keeps opt-out but allows explicit enable in same auth session',async()=>{const store=new Map([['pablicus:push-owner',A]]),f=fixture({store});let g;try{await f.client.refresh();await f.client.disable();f.dispose();g=fixture({store,lost:true});await g.client.sessionRestored(g.session());assert.equal(g.client.enabled,false);await g.client.enable();assert.equal(g.client.enabled,true);}finally{f.dispose();g?.dispose();}});
await test('double logout cleanup preserves fence and new login session restores consent',async()=>{const f=fixture();const jwt=sid=>'e30.'+Buffer.from(JSON.stringify({session_id:sid})).toString('base64url')+'.SYNTHETIC';try{f.setToken(jwt(I));await f.client.sessionRestored(f.session());assert.equal(f.client.enabled,true);await f.client.signOut();await f.client.clear();f.setUser(null);f.setUser(A);f.setToken(jwt(B));await f.client.sessionRestored(f.session());assert.equal(f.client.enabled,true);assert.equal(f.worker.at(-1).recipientId,A);}finally{f.dispose();}});
mkdirSync('results',{recursive:true});writeFileSync('results/r2-client-tests.json',JSON.stringify({passed:checks.filter(x=>x.passed).length,failed:checks.filter(x=>!x.passed).length,checks,boundary:'Real client functions in Node VM; synthetic clock, auth, Web Locks, PushManager, worker messaging, and network. No device delivery claim.'},null,2));
if(checks.some(x=>!x.passed))process.exitCode=1;
