// Executes the retained 27 R2 cases, then the new R3 checks. All network/provider boundaries are synthetic.
import {fixture,flush} from '../pablicus-r2/test_client.mjs';
import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
const checks=[];
async function test(name,fn){try{await fn();checks.push({name,passed:true});console.log('PASS '+name);}catch(e){checks.push({name,passed:false,error:e.stack});console.error('FAIL '+name+': '+e.message);}}
const healthCalls=f=>f.calls.filter(c=>c.body?.action==='client_health');
await test('existing consented subscription binds locally despite failed config network',async()=>{const f=fixture({failNetwork:true});try{await f.client.refresh();assert.equal(f.worker[0]?.type,'PABLICUS_PUSH_BIND');assert.equal(f.worker[0]?.recipientId,f.session().user.id);assert.equal(f.counts.subscribes,0);assert.equal(f.unsubscribed.length,0);assert.equal(f.client.enabled,false);}finally{f.dispose();}});
await test('explicit opt-out never locally binds or subscribes on network failure',async()=>{const f=fixture({failNetwork:true,disabled:true});try{await f.client.refresh();assert.equal(f.worker.length,0);assert.equal(f.counts.subscribes,0);}finally{f.dispose();}});
await test('health reports missing consent without changing it or prompting',async()=>{const f=fixture({health:true,noConsent:true,lost:true});try{await f.client.sessionRestored(f.session());await f.client.reportHealth();await flush();const h=healthCalls(f)[0].body.health;assert.equal(h.consent,'unknown');assert.equal(h.subscription,'missing');assert.equal(h.owner,'missing');assert.equal(f.counts.permissionRequests,0);assert.equal(f.counts.subscribes,0);assert.equal(f.store.has('pablicus:r2:consent:'+f.session().user.id),false);}finally{f.dispose();}});
await test('health preserves denied and disabled settings',async()=>{const f=fixture({health:true,permission:'denied',disabled:true});try{await f.client.sessionRestored(f.session());await f.client.reportHealth();await flush();const h=healthCalls(f)[0].body.health;assert.equal(h.permission,'denied');assert.equal(h.consent,'disabled');assert.equal(f.counts.subscribes,0);assert.equal(f.counts.permissionRequests,0);}finally{f.dispose();}});
await test('health separates page build from active worker build and omits capabilities',async()=>{const f=fixture({health:true});try{await f.client.refresh();await f.client.reportHealth();const call=healthCalls(f)[0];assert.equal(call.body.health.worker_build,'git:'+'f'.repeat(40));assert.equal(call.body.health.registration,'current');assert.equal(call.body.health.subscription,'present');const body=JSON.stringify(call.body);for(const secret of ['USER_JWT_A',f.initial.endpoint,'p256dh','auth_key'])assert.equal(body.includes(secret),false);assert.equal(f.worker.some(x=>JSON.stringify(x).includes('USER_JWT_A')),false);}finally{f.dispose();}});
await test('diagnostic lifecycle bursts are rate limited',async()=>{const f=fixture({health:true});try{await f.client.refresh();await f.client.reportHealth();for(let i=0;i<20;i++){f.dispatch('pageshow');f.dispatch('online');await f.client.reportHealth();}await flush();assert.equal(healthCalls(f).length,1);}finally{f.dispose();}});
await test('diagnostics distinguish registration scope mismatch without binding it',async()=>{const f=fixture({health:true,wrongScope:true});try{const h=await f.client.localHealth();assert.equal(h.registration,'mismatch');assert.equal(h.worker_build,null);assert.equal(f.worker.length,0);}finally{f.dispose();}});
await test('diagnostic failure cannot break local repair or erase consent',async()=>{const f=fixture({health:true,failNetwork:true});try{await f.client.refresh();await f.client.reportHealth();assert.equal(f.worker[0].recipientId,f.session().user.id);assert.equal(f.store.get('pablicus:push-owner'),f.session().user.id);assert.equal(f.counts.subscribes,0);}finally{f.dispose();}});
writeFileSync('results/r3-client-health.json',JSON.stringify({passed:checks.filter(x=>x.passed).length,failed:checks.filter(x=>!x.passed).length,checks,boundary:'Actual client module in VM; synthetic browser/auth/network. No real device delivery proof.'},null,2));
if(checks.some(x=>!x.passed))process.exitCode=1;
