import {initialize} from './assets/ui/app.mjs';
let turns=[],calls=0,finish=null,rejectSend=null,fail=false;
window.SekkesS2={updateReady:false,busy:false,voiceActive:false,saveDraft(){},ownerRequest:async(p,b)=>{if(p==='status')return {owner:true,active:true};if(p==='chat'){calls++;if(fail)throw Error('OFFLINE');turns=[{id:b.id,user_text:b.text,attachments:[],status:'pending',created_at:new Date().toISOString()}];await new Promise(r=>finish=r);turns[0]={...turns[0],status:'completed',reply:'Ответ',answered_at:new Date().toISOString()};return {};}return {turns:structuredClone(turns),media:[],documents:[],costs:{},budget_cap_usd:1};}};
initialize();const wait=async(fn)=>{const end=Date.now()+20000;while(!fn()){if(Date.now()>end)throw Error('Timeout');await new Promise(r=>setTimeout(r,100));}};await wait(()=>window.SekkesUI);SekkesUI.account({id:'synthetic-qa'});location.hash='admin';
document.querySelector('#runCheck').onclick=async()=>{const out=document.querySelector('#testResults');const check=(n,v)=>{out.textContent+=(v?'PASS ':'FAIL ')+n+'\n';if(!v)throw Error(n)};try{await wait(()=>document.querySelector('.owner-composer'));let input=document.querySelector('.owner-composer textarea');const text=Array(12).fill('Длинное задание для агента.').join('\n');input.value=text;input.dispatchEvent(new Event('input'));const height=input.style.height;const form=document.querySelector('.owner-composer');form.requestSubmit();form.requestSubmit();
check('draft cleared before response',input.value==='');check('same textarea stays mounted',input===document.querySelector('.owner-composer textarea'));check('composer shrinks immediately',parseFloat(input.style.height)<parseFloat(height));check('one request for double submit',calls===1);check('one outgoing message',document.querySelectorAll('.owner-user').length===1);check('send button hidden',document.querySelector('.owner-send').hidden);
input.value='Следующий черновик';input.dispatchEvent(new Event('input'));finish();await wait(()=>document.querySelector('.owner-screen').getAttribute('aria-busy')==='false');check('new draft survives late response',document.querySelector('.owner-composer textarea').value==='Следующий черновик');
fail=true;turns=[];document.querySelector('.owner-composer').requestSubmit();await wait(()=>document.querySelector('.owner-screen').getAttribute('aria-busy')==='false');check('failed message remains visible',!!document.querySelector('.owner-failed'));check('failed message has retry',!![...document.querySelectorAll('.owner-failed button')].find(n=>n.textContent==='Повторить сообщение'));check('failed submission not left duplicated in composer',document.querySelector('.owner-composer textarea').value==='');
}catch(e){out.textContent+='ERROR '+e.message;console.error(e)}};
