import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync(new URL('../../vision-talk/pablicus/contact-discovery.js',import.meta.url),'utf8');
class Element{
 constructor(tag){this.tagName=tag;this.children=[];this.dataset={};this.isConnected=false;this.open=false;this.listeners={};this.textContent='';}
 append(...nodes){for(const node of nodes){node.parent=this;node.isConnected=true;this.children.push(node);}}
 replaceChildren(...nodes){this.children=[];this.append(...nodes);}
 setAttribute(k,v){this[k]=v;} addEventListener(k,v){this.listeners[k]=v;}showModal(){this.open=true;}close(){this.open=false;}focus(){}remove(){this.parent.children=this.parent.children.filter(n=>n!==this);}
}
function fixture({contacts,reply,clock}={}){let user={id:'owner'};const calls=[],body=new Element('body'),window={navigator:{contacts},document:null};const document={body,createElement:t=>new Element(t),activeElement:null};window.document=document;vm.runInNewContext(source,{window,document,setTimeout:clock||setTimeout,clearTimeout,console});const state={search_enabled:true,discoverable_email:false,discoverable_phone:false,verified_email:true,verified_phone:false,revision:1,hidden:[]};const api=window.PablicusContactDiscovery.create({client:{rpc:async(name,args)=>{calls.push(args);return reply?reply(args,state):{data:state};}},getUser:()=>user,onOpen:()=>{calls.push('open');},onSearch:()=>calls.push('search'),onShare:()=>calls.push('share')});api.mount(body);const panel=body.children.find(n=>n.tagName==='dialog');const all=()=>{const out=[];function walk(n){out.push(n);n.children.forEach(walk);}walk(panel);return out;};return{api,panel,calls,state,all,setUser:x=>{user=x;},button:text=>all().find(n=>n.tagName==='button'&&n.textContent===text),status:()=>all().find(n=>n.role==='status')};}
const tick=()=>new Promise(r=>setTimeout(r,0));
const picker=values=>({getProperties:async()=>['name','tel','email'],select:async props=>{assert.deepEqual(Array.from(props),['tel','email']);return values;}});
test('unsupported picker keeps name search and share available',async()=>{const f=fixture();await f.api.open();assert.equal(f.button('Выбрать контакты').disabled,true);f.button('Поиск по имени').onclick();assert.equal(f.panel.open,false);assert.equal(f.calls.at(-1),'search');});
test('picker selection does not upload until reviewed',async()=>{const f=fixture({contacts:picker([{email:['fixture@example.test'],name:['Never request']}]),reply:args=>({data:args.p_action==='match'?{matches:[]}:{search_enabled:true,verified_email:true,revision:3}})});await f.api.open();await tick();await f.button('Выбрать контакты').onclick();assert.equal(f.calls.length,1);assert.equal(f.button('Найти выбранные контакты').disabled,false);f.button('Найти выбранные контакты').onclick();await tick();assert.equal(f.calls[1].p_action,'match');assert.equal(f.calls[1].p_input.identifiers[0].value,'fixture@example.test');});
test('cancel drops selection',async()=>{const f=fixture({contacts:picker([{tel:['+12025550123']}])});await f.api.open();await tick();await f.button('Выбрать контакты').onclick();f.button('Отменить выбор').onclick();assert.equal(f.button('Найти выбранные контакты').disabled,true);assert.equal(f.calls.length,1);});
test('empty picker and over-limit selection never upload',async()=>{for(const values of [[],[{email:Array.from({length:21},(_,i)=>`${i}@example.test`)}]]){const f=fixture({contacts:picker(values)});await f.api.open();await tick();await f.button('Выбрать контакты').onclick();assert.equal(f.button('Найти выбранные контакты').disabled,true);assert.equal(f.calls.length,1);}});
test('preferences include revision and no implicit discoverability',async()=>{const f=fixture();await f.api.open();const form=f.all().find(n=>n.tagName==='form');form.onsubmit({preventDefault(){}});await tick();assert.equal(f.calls[1].p_input.expected_revision,1);assert.equal(f.calls[1].p_input.discoverable_email,false);assert.equal(f.calls[1].p_input.discoverable_phone,false);});
test('revocation disables picker',async()=>{const f=fixture({contacts:picker([])});f.state.search_enabled=false;await f.api.open();await tick();assert.equal(f.button('Выбрать контакты').disabled,true);});
test('late state response after logout never repaints',async()=>{let finish;const f=fixture({reply:()=>new Promise(r=>{finish=r;})});const pending=f.api.open();f.setUser(null);f.api.clear();finish({data:{search_enabled:true}});await pending;assert.equal(f.panel.open,false);assert.equal(f.button('Выбрать контакты').disabled,true);});
test('late selection after account switch is discarded',async()=>{let finish;const f=fixture({contacts:{getProperties:async()=>['email'],select:()=>new Promise(r=>{finish=r;})}});await f.api.open();await tick();const pending=f.button('Выбрать контакты').onclick();f.setUser({id:'other'});finish([{email:['fixture@example.test']}]);await pending;assert.equal(f.panel.open,false);assert.equal(f.calls.length,1);});
test('errors never render backend details',async()=>{const f=fixture({reply:()=>({error:{message:'SECRET user@example.test'}})});await f.api.open();assert.ok(!f.status().textContent.includes('SECRET'));assert.ok(!f.status().textContent.includes('@'));});
test('hide and unhide use explicit targets and state',async()=>{const f=fixture({reply:(args,state)=>({data:args.p_action==='unhide'?{...state,hidden:[]}:state})});f.state.hidden=[{id:'target',display_name:'Fixture'}];await f.api.open();f.button('Вернуть в поиск').onclick();await tick();assert.equal(f.calls[1].p_action,'unhide');assert.equal(f.calls[1].p_input.target_id,'target');assert.equal(f.button('Вернуть в поиск'),undefined);});
test('structured failure never paints successful preferences',async()=>{const f=fixture({reply:(args,state)=>({data:args.p_action==='preferences'?{ok:false,error:'verification_required'}:state})});await f.api.open();f.all().find(n=>n.tagName==='form').onsubmit({preventDefault(){}});await tick();assert.ok(f.status().textContent.includes('Сначала подтвердите'));});
test('conflict reloads current settings without resubmitting stale opt-ins',async()=>{const f=fixture({reply:(args,state)=>({data:args.p_action==='preferences'?{ok:false,error:'conflict'}:{...state,revision:7,search_enabled:false}})});await f.api.open();f.all().find(n=>n.name==='search_enabled').checked=true;f.all().find(n=>n.tagName==='form').onsubmit({preventDefault(){}});await tick();assert.deepEqual(f.calls.map(x=>x.p_action),['state','preferences','state']);assert.equal(f.all().find(n=>n.name==='search_enabled').checked,false);});
test('duplicate confirmation submits exactly once',async()=>{let finish;const f=fixture({contacts:picker([{email:['fixture@example.test']}]),reply:(args,state)=>args.p_action==='match'?new Promise(r=>{finish=r;}):{data:state}});await f.api.open();await tick();await f.button('Выбрать контакты').onclick();f.button('Найти выбранные контакты').onclick();f.button('Найти выбранные контакты').onclick();assert.equal(f.calls.filter(x=>x.p_action==='match').length,1);finish({data:{matches:[]}});await tick();});
test('late match and preferences cannot repaint switched account',async()=>{for(const action of ['match','preferences']){let finish;const f=fixture({contacts:picker([{email:['fixture@example.test']}]),reply:(args,state)=>args.p_action===action?new Promise(r=>{finish=r;}):{data:state}});await f.api.open();await tick();if(action==='match'){await f.button('Выбрать контакты').onclick();f.button('Найти выбранные контакты').onclick();}else f.all().find(n=>n.tagName==='form').onsubmit({preventDefault(){}});f.setUser({id:'other'});finish({data:{...f.state,matches:[{id:'target',display_name:'Never render'}]}});await tick();assert.equal(f.panel.open,false);assert.equal(f.button('Never render'),undefined);}});

test('RPC timeout ends loading without exposing identifiers',async()=>{let fire;const f=fixture({reply:()=>new Promise(()=>{}),clock:(callback,delay)=>{assert.equal(delay,10000);fire=callback;return 12345;}});const pending=f.api.open();fire();await pending;assert.ok(f.status().textContent.includes('Не удалось'));assert.equal(f.button('Сохранить согласия').disabled,true);});
test('unverified phone never retains stale checked consent',async()=>{const f=fixture();f.state.discoverable_phone=true;await f.api.open();assert.equal(f.all().find(n=>n.name==='discoverable_phone').checked,false);});
